import { COMEBACK_CITY_AUTHORED } from './courseV2Authored.js';

export const CourseV2Definition = Object.freeze({
  key: 'string',
  version: 'string',
  laps: 'number',
  centerline: 'Array<{ x: number, z: number }>',
  roadRibbons: 'RoadRibbon[]',
  branches: 'RouteBranch[]',
  surfaceZones: 'SurfaceZone[]',
  collisionZones: 'CollisionZone[]',
  sceneryAnchors: 'Array<object>',
  districtAnchors: 'DistrictAnchor[]',
  minimapPath: 'Array<{ x: number, z: number }>',
  cameraCheckpoints: 'Array<object>',
});

export const RoadRibbon = Object.freeze({
  key: 'string',
  role: 'main | branch',
  width: 'number',
  shoulderWidth: 'number',
});

export const RouteBranch = Object.freeze({
  key: 'string',
  name: 'string',
  startProgress: 'number',
  endProgress: 'number',
  width: 'number',
  leadSeconds: 'number',
  points: 'Array<{ x: number, z: number }>',
});

export const SurfaceZone = Object.freeze({
  key: 'string',
  type: 'asphalt | boost | offroad | wet',
  progress: 'number',
  radius: 'number',
});

export const CollisionZone = Object.freeze({
  key: 'string',
  shape: 'circle | box',
  position: '{ x: number, z: number }',
  radius: 'number',
});

export const DistrictAnchor = Object.freeze({
  key: 'string',
  label: 'string',
  progress: 'number',
  side: 'number',
  setback: 'number',
});

export const AssetManifestEntry = Object.freeze({
  filePath: 'string',
  source: 'string',
  license: 'string',
  role: 'string',
  sizeBudget: 'string',
  fallback: 'string',
});

export const RaceVisualTelemetry = Object.freeze({
  kartScreenCoverage: '{ heightRatio: number, centerYRatio: number, framingBandFromBottom: number }',
  roadAheadCoverage: '{ value: number, samples: number }',
  visibleBranchCount: 'number',
  activeSurface: 'string',
  offroadSlowdown: 'number',
  driftTier: 'number',
  boostTimer: 'number',
  cameraClipCount: 'number',
  nearestCollisionDistance: 'number',
  fps: 'number',
  assetLoadState: '{ state: string, manifestPath: string, externalAssets: number }',
});

export const KartTuningV2 = Object.freeze({
  acceleration: 58,
  boostDurations: [0.35, 0.75, 1.1],
  boostStrength: [9.5, 14.5, 20],
  driftGrip: 4.05,
  grip: 14.2,
  maxSpeed: 58,
  offroadMultiplier: 0.46,
  slideAngle: 0.28,
  slideForce: 10.8,
  steering: 2.46,
  tierChargeTimes: [0.55, 1.3, 2.15],
});

// custom-comeback-city-pass Stage 1 (2026-07-20): the course is now the
// authored six-district custom map generated by
// scripts/author-comeback-city-course.mjs (straight/arc primitives + Dubins
// return, closed exactly, validated for curvature/crossings/markers). The
// generated data lives in courseV2Authored.js; this file assembles the
// CourseV2Definition shape the runtime and gate scripts consume.
const centerline = COMEBACK_CITY_AUTHORED.centerline.map((point) => ({ ...point }));

const minimapPath = centerline.map((point) => ({ ...point }));

export const COMEBACK_CITY_COURSE_V2 = Object.freeze({
  key: 'comeback-city',
  version: 'v2-authored-kart',
  laps: 3,
  kartOnly: true,
  mainRoadWidth: 56,
  sampleCount: 132,
  startProgress: 0.012,
  startLabel: 'Ice Plaza',
  centerline,
  minimapPath,
  roadRibbons: COMEBACK_CITY_AUTHORED.roadRibbons,
  branches: [],
  surfaceZones: COMEBACK_CITY_AUTHORED.surfaceZones,
  boostPads: COMEBACK_CITY_AUTHORED.boostPads,
  itemBoxes: COMEBACK_CITY_AUTHORED.itemBoxes,
  bananaPlacements: COMEBACK_CITY_AUTHORED.bananaPlacements,
  districtAnchors: COMEBACK_CITY_AUTHORED.districtAnchors,
  collisionZones: COMEBACK_CITY_AUTHORED.collisionZones,
  sceneryAnchors: COMEBACK_CITY_AUTHORED.sceneryAnchors,
  cameraCheckpoints: COMEBACK_CITY_AUTHORED.cameraCheckpoints,
  // Custom-map extensions (same module of truth for the runtime builders):
  worldBounds: COMEBACK_CITY_AUTHORED.worldBounds,
  courseMetrics: COMEBACK_CITY_AUTHORED.metrics,
  assetLoadState: {
    state: 'procedural-ready',
    manifestPath: '/src/assets/game/asset-manifest.json',
    externalAssets: 0,
    missing: [],
  },
});

export const COMEBACK_CITY_TRACK_V2_FIELDS = Object.freeze({
  bananaPlacements: COMEBACK_CITY_COURSE_V2.bananaPlacements,
  boostPads: COMEBACK_CITY_COURSE_V2.boostPads,
  itemBoxes: COMEBACK_CITY_COURSE_V2.itemBoxes,
  shortcuts: COMEBACK_CITY_COURSE_V2.branches.map((branch) => ({
    accent: branch.accent,
    decisionCueProgress: branch.decisionCueProgress,
    endProgress: branch.endProgress,
    entrySide: branch.entrySide,
    key: branch.key,
    label: branch.label,
    leadSeconds: branch.leadSeconds,
    name: branch.name,
    points: branch.points,
    shoulderWidth: branch.shoulderWidth,
    startProgress: branch.startProgress,
    width: branch.width,
  })),
});
