export const CourseV2Definition = Object.freeze({
  key: 'string',
  version: 'string',
  laps: 'number',
  centerline: 'Array<{ x: number, z: number }>',
  roadRibbons: 'RoadRibbon[]',
  branches: 'RouteBranch[]',
  surfaceZones: 'SurfaceZone[]',
  collisionZones: 'CollisionZone[]',
  sceneryAnchors: 'Array<object>',
  districtAnchors: 'DistrictAnchor[]',
  minimapPath: 'Array<{ x: number, z: number }>',
  cameraCheckpoints: 'Array<object>',
});

export const RoadRibbon = Object.freeze({
  key: 'string',
  role: 'main | branch',
  width: 'number',
  shoulderWidth: 'number',
});

export const RouteBranch = Object.freeze({
  key: 'string',
  name: 'string',
  startProgress: 'number',
  endProgress: 'number',
  width: 'number',
  leadSeconds: 'number',
  points: 'Array<{ x: number, z: number }>',
});

export const SurfaceZone = Object.freeze({
  key: 'string',
  type: 'asphalt | boost | offroad | wet',
  progress: 'number',
  radius: 'number',
});

export const CollisionZone = Object.freeze({
  key: 'string',
  shape: 'circle | box',
  position: '{ x: number, z: number }',
  radius: 'number',
});

export const DistrictAnchor = Object.freeze({
  key: 'string',
  label: 'string',
  progress: 'number',
  side: 'number',
  setback: 'number',
});

export const AssetManifestEntry = Object.freeze({
  filePath: 'string',
  source: 'string',
  license: 'string',
  role: 'string',
  sizeBudget: 'string',
  fallback: 'string',
});

export const RaceVisualTelemetry = Object.freeze({
  kartScreenCoverage: '{ heightRatio: number, centerYRatio: number, framingBandFromBottom: number }',
  roadAheadCoverage: '{ value: number, samples: number }',
  visibleBranchCount: 'number',
  activeSurface: 'string',
  offroadSlowdown: 'number',
  driftTier: 'number',
  boostTimer: 'number',
  cameraClipCount: 'number',
  nearestCollisionDistance: 'number',
  fps: 'number',
  assetLoadState: '{ state: string, manifestPath: string, externalAssets: number }',
});

export const KartTuningV2 = Object.freeze({
  acceleration: 58,
  boostDurations: [0.35, 0.75, 1.1],
  boostStrength: [9.5, 14.5, 20],
  driftGrip: 4.05,
  grip: 14.2,
  maxSpeed: 58,
  offroadMultiplier: 0.46,
  slideAngle: 0.28,
  slideForce: 10.8,
  steering: 2.46,
  tierChargeTimes: [0.55, 1.3, 2.15],
});

const centerline = [
  { x: -246, z: 126 },
  { x: -156, z: 108 },
  { x: -48, z: 86 },
  { x: 78, z: 42 },
  { x: 166, z: -50 },
  { x: 126, z: -144 },
  { x: 10, z: -212 },
  { x: -126, z: -178 },
  { x: -224, z: -80 },
  { x: -178, z: 38 },
  { x: -58, z: 0 },
  { x: 42, z: -66 },
  { x: 166, z: -22 },
  { x: 250, z: 58 },
  { x: 282, z: 156 },
  { x: 196, z: 236 },
  { x: 62, z: 268 },
  { x: -86, z: 238 },
  { x: -206, z: 184 },
];

const minimapPath = centerline.map((point) => ({ ...point }));

export const COMEBACK_CITY_COURSE_V2 = Object.freeze({
  key: 'comeback-city',
  version: 'v2-authored-kart',
  laps: 3,
  kartOnly: true,
  mainRoadWidth: 50,
  sampleCount: 132,
  startProgress: 0.012,
  startLabel: 'Start Boulevard',
  centerline,
  minimapPath,
  roadRibbons: [
    { key: 'start-boulevard', role: 'main', width: 52, shoulderWidth: 6.5, startProgress: 0, endProgress: 0.13 },
    { key: 'gym-sweeper', role: 'main', width: 50, shoulderWidth: 6, startProgress: 0.13, endProgress: 0.28 },
    { key: 'food-fork-main', role: 'main', width: 48, shoulderWidth: 6, startProgress: 0.28, endProgress: 0.43 },
    { key: 'lab-bridge-s-turn', role: 'main', width: 46, shoulderWidth: 5.8, startProgress: 0.43, endProgress: 0.64 },
    { key: 'clinic-plaza-loop', role: 'main', width: 54, shoulderWidth: 6.8, startProgress: 0.64, endProgress: 0.82 },
    { key: 'finish-roundabout', role: 'main', width: 56, shoulderWidth: 7, startProgress: 0.82, endProgress: 1 },
  ],
  branches: [],
  surfaceZones: [
    { key: 'start-asphalt', type: 'asphalt', progress: 0.04, radius: 120 },
    { key: 'food-wet-cleanup', type: 'wet', progress: 0.335, side: -8, radius: 16 },
    { key: 'lab-bridge-grip', type: 'asphalt', progress: 0.57, radius: 80 },
    { key: 'clinic-clean-tile', type: 'wet', progress: 0.72, side: 7, radius: 15 },
    { key: 'waterfront-offroad-edge', type: 'offroad', progress: 0.88, side: 31, radius: 26 },
  ],
  boostPads: [
    { key: 'start-boulevard-pad', progress: 0.055, side: 0 },
    { key: 'gym-exit-pad', progress: 0.215, side: 0.18 },
    { key: 'lab-exit-pad', progress: 0.61, side: -0.16 },
    { key: 'waterfront-pad', progress: 0.875, side: 0.12 },
  ],
  itemBoxes: [
    { progress: 0.09, side: -0.2 },
    { progress: 0.19, side: 0.18 },
    { progress: 0.31, side: -0.18 },
    { progress: 0.45, side: 0.16 },
    { progress: 0.59, side: -0.18 },
    { progress: 0.72, side: 0.2 },
    { progress: 0.84, side: -0.16 },
    { progress: 0.95, side: 0.14 },
  ],
  bananaPlacements: [
    { progress: 0.045, side: -0.18 },
    { progress: 0.095, side: 0.18 },
    { progress: 0.15, side: -0.08 },
    { progress: 0.205, side: 0.22 },
    { progress: 0.265, side: -0.2 },
    { progress: 0.325, side: 0.12 },
    { progress: 0.385, side: -0.18 },
    { progress: 0.445, side: 0.22 },
    { progress: 0.505, side: -0.1 },
    { progress: 0.565, side: 0.16 },
    { progress: 0.625, side: -0.2 },
    { progress: 0.685, side: 0.12 },
    { progress: 0.745, side: -0.16 },
    { progress: 0.805, side: 0.2 },
    { progress: 0.865, side: -0.14 },
    { progress: 0.925, side: 0.18 },
    { progress: 0.965, side: -0.08 },
    { progress: 0.99, side: 0.12 },
  ],
  districtAnchors: [
    {
      key: 'gym',
      accent: '#80ff62',
      base: '#3ca75b',
      dark: '#1f5f35',
      icon: 'dumbbell',
      label: 'GYM',
      progress: 0.18,
      roof: '#e9f7ce',
      setback: 86,
      side: 1,
    },
    {
      key: 'food',
      accent: '#ffac32',
      base: '#f28b2e',
      dark: '#9d4516',
      icon: 'utensils',
      label: 'FOOD COURT',
      progress: 0.31,
      roof: '#fff0b0',
      setback: 84,
      side: -1,
    },
    {
      key: 'lab',
      accent: '#d45cff',
      base: '#8a53df',
      dark: '#38206f',
      icon: 'flask',
      label: 'LAB',
      progress: 0.56,
      roof: '#f0e2ff',
      setback: 92,
      side: 1,
    },
    {
      key: 'clinic',
      accent: '#ff5b68',
      base: '#e64b4b',
      dark: '#7c202c',
      icon: 'cross',
      label: 'CLINIC',
      progress: 0.72,
      roof: '#f3ece0',
      setback: 88,
      side: -1,
    },
    {
      key: 'garage',
      accent: '#2cc8ff',
      base: '#2677d8',
      dark: '#143d78',
      icon: 'wrench',
      label: 'GARAGE',
      progress: 0.88,
      roof: '#e4f8ff',
      setback: 92,
      side: 1,
    },
  ],
  collisionZones: [
    { key: 'gym-facade', shape: 'circle', position: { x: 128, z: -20 }, radius: 24 },
    { key: 'food-stalls', shape: 'circle', position: { x: 22, z: -208 }, radius: 28 },
    { key: 'lab-tower', shape: 'circle', position: { x: -32, z: 96 }, radius: 28 },
    { key: 'clinic-plaza-building', shape: 'circle', position: { x: 318, z: 126 }, radius: 26 },
    { key: 'garage-waterfront-building', shape: 'circle', position: { x: -72, z: 352 }, radius: 28 },
    { key: 'finish-roundabout-core', shape: 'circle', position: { x: -224, z: 150 }, radius: 22 },
  ],
  sceneryAnchors: [
    { kind: 'water', x: -58, z: 322, w: 210, d: 96, color: '#0ea5c8' },
    { kind: 'bridge', x: 18, z: 42, w: 126, d: 18, color: '#65717f' },
    { kind: 'roundabout', x: -226, z: 150, r: 38, color: '#2cc8ff' },
    { kind: 'skyline', x: 48, z: -318, w: 520, d: 64, color: '#315b8d' },
  ],
  cameraCheckpoints: [
    { key: 'mobile-start', profile: 'mobile', progress: 0.04, targetBandFromBottom: [0.25, 0.33] },
    { key: 'desktop-start', profile: 'desktop', progress: 0.04, targetBandFromBottom: [0.14, 0.22] },
    { key: 'early-route-readability', profile: 'all', progress: 0.245 },
    { key: 'camera-near-lab', profile: 'all', progress: 0.56, collisionClearanceMin: 1.5 },
  ],
  assetLoadState: {
    state: 'procedural-ready',
    manifestPath: '/src/assets/game/asset-manifest.json',
    externalAssets: 0,
    missing: [],
  },
});

export const COMEBACK_CITY_TRACK_V2_FIELDS = Object.freeze({
  bananaPlacements: COMEBACK_CITY_COURSE_V2.bananaPlacements,
  boostPads: COMEBACK_CITY_COURSE_V2.boostPads,
  itemBoxes: COMEBACK_CITY_COURSE_V2.itemBoxes,
  shortcuts: COMEBACK_CITY_COURSE_V2.branches.map((branch) => ({
    accent: branch.accent,
    decisionCueProgress: branch.decisionCueProgress,
    endProgress: branch.endProgress,
    entrySide: branch.entrySide,
    key: branch.key,
    label: branch.label,
    leadSeconds: branch.leadSeconds,
    name: branch.name,
    points: branch.points,
    shoulderWidth: branch.shoulderWidth,
    startProgress: branch.startProgress,
    width: branch.width,
  })),
});
