export const RACE_TRACKS = [
  {
    key: 'tide-pier',
    name: 'Tide Pier',
    shortName: 'Tide Pier',
    discipline: 'Switching',
    difficulty: 'Beginner',
    difficultyWhy: 'Forgiving turns, clear route identity, and low hazard density teach when to switch between kart and plane.',
    laps: 3,
    width: 96,
    bananaCount: 10,
    bananaPlacements: [
      { progress: 0.06, side: -0.16 },
      { progress: 0.14, side: 0.12 },
      { progress: 0.24, side: -0.18 },
      { progress: 0.34, side: 0.16 },
      { progress: 0.44, side: -0.1 },
      { progress: 0.54, side: 0.18 },
      { progress: 0.64, side: -0.16 },
      { progress: 0.74, side: 0.14 },
      { progress: 0.84, side: -0.12 },
      { progress: 0.94, side: 0.16 },
    ],
    startProgress: 0.82,
    raceStyle: 'technical',
    accent: '#ffbf6b',
    asphalt: '#6f6656',
    curbA: '#fff4d6',
    curbB: '#2cc8ff',
    grass: '#2e7d72',
    hazard: '#0b5f7a',
    sky: '#f6a35f',
    theme: {
      atmosphere: 'Working coastal pier town with fishing boats, market stalls, rope piles, gulls, and drying laundry.',
      time: 'Golden hour',
      weather: 'Warm salt air, soft spray, and a rising tide by lap three',
      music: 'Relaxed island groove that builds with gull cries and distant boat horns',
    },
    layout: {
      philosophy: 'Teach vehicle switching without punishing experimentation.',
      shape: 'A figure-8 coastal route with a bridge crossing, a narrow fish market, a pier launch, and a beach return.',
      keyTurns: ['Fish-market S-bend', 'Lighthouse base loop', 'Beach landing bend'],
      elevation: ['Ground route crosses under the pier', 'Air route rises over the harbor', 'Hybrid route launches to the island and returns to the beach'],
      branches: [
        'Ground layer is safest through town.',
        'Air layer clears harbor hazards but must dodge lighthouse beam and gulls.',
        'Hybrid layer uses the pier ramp to reach the island rare boxes.',
      ],
    },
    landmarks: [
      'Massive lighthouse visible from anywhere on the track',
      'Fishing pier with bobbing boats',
      'Cliffside fish market',
      'Distant island halfway point for the hybrid route',
    ],
    signatureObstacles: [
      'Sliding fish carts push karts off the racing line on a readable timer.',
      'Hanging laundry briefly obscures vision through the fish market.',
      'The rotating lighthouse beam blinds plane racers in its arc for three seconds.',
      'Seagull flocks disperse on contact but cause a spin-out.',
      'Crab traps slow karts that clip the inside of beach turns.',
    ],
    dynamicElements: [
      'Rising tide expands water hazards each lap and activates flooded shortcut zones by lap three.',
      'Boat traffic crosses under the pier on a timer and blocks the low shortcut.',
      'Captain Brine can ring the dock bell to summon seagulls early while in second place.',
    ],
    riskRewardShortcut: {
      name: 'Pier Jump',
      summary: 'A boost-speed jump off the end of the pier toward the harbor line. Hit it cleanly for a faster crossing; miss it and the reset costs about four seconds.',
    },
    powerUpIntel: {
      placement: 'Six ground boxes split between safe market exits and risky inside lines, four air boxes in lighthouse and gull gaps, and two rare boxes on the hybrid island path.',
      signatureUse: 'Anchor Drop protects narrow alley entrances by dragging a kart backward when it drives over the embedded anchor.',
      defensive: 'At fish-market entry, lighthouse base, and beach landing.',
      aggressive: 'Before the pier jump and the air-route lighthouse gap.',
    },
    aiIntel: {
      line: 'Default racing line stays on the ground route.',
      shortcuts: 'Rivals switch to plane on lap two if the rising tide blocks the shortcut.',
      items: 'Anchor Drop is used defensively at market and alley entrances.',
      signatureMove: 'Captain Brine rings the dock bell to summon seagulls early when he is in second place.',
    },
    signatureItem: {
      key: 'anchorDrop',
      name: 'Anchor Drop',
      summary: 'Kart-only trap that sinks into the road and drags the next opponent backward three meters.',
      color: '#38506b',
    },
    boostPads: [0.095, 0.585, 0.742],
    itemBoxes: [0.08, 0.18, 0.32, 0.48, 0.68, 0.88],
    layers: {
      ground: {
        name: 'Fish-market ground line',
        vehiclePreference: 'kart',
        aiWeight: 1.14,
        lineOffset: -0.08,
        itemBoxes: [
          { progress: 0.08, side: -0.22 },
          { progress: 0.18, side: 0.18 },
          { progress: 0.32, side: -0.26 },
          { progress: 0.48, side: 0.2 },
          { progress: 0.68, side: -0.2 },
          { progress: 0.88, side: 0.22 },
        ],
      },
      air: {
        name: 'Harbor air line',
        vehiclePreference: 'plane',
        aiWeight: 0.88,
        lineOffset: 0.44,
        itemBoxes: [
          { progress: 0.21, side: 0.3 },
          { progress: 0.39, side: 0.34 },
          { progress: 0.57, side: 0.3 },
          { progress: 0.79, side: 0.32 },
        ],
      },
      hybrid: {
        name: 'Island launch route',
        vehiclePreference: 'hover',
        aiWeight: 0.98,
        lineOffset: -0.38,
        itemBoxes: [
          { progress: 0.63, side: -0.36, rare: true, pool: ['anchorDrop', 'invincibility', 'bananaMagnet'] },
          { progress: 0.735, side: -0.34, rare: true, pool: ['anchorDrop', 'ghostReplay', 'boost'] },
        ],
      },
    },
    switchPads: [
      { key: 'pier-launch-plane-pad', progress: 0.585, targetVehicle: 'plane', layer: 'hybrid', radius: 8 },
      { key: 'island-hover-pad', progress: 0.685, targetVehicle: 'hover', layer: 'hybrid', radius: 8 },
      { key: 'beach-landing-kart-pad', progress: 0.76, targetVehicle: 'kart', layer: 'ground', radius: 8 },
      { key: 'lap-three-flood-plane-pad', progress: 0.36, targetVehicle: 'plane', layer: 'air', radius: 9 },
    ],
    vehicleZones: [
      { key: 'fish-market-kart-only', progress: 0.24, vehicle: 'kart', action: 'block', radius: 15 },
      { key: 'harbor-air-only', progress: 0.62, vehicle: 'plane', action: 'auto-switch', radius: 18 },
      { key: 'lap-three-flooded-ground', progress: 0.34, vehicle: 'plane', action: 'auto-switch', radius: 18, active: false },
      { key: 'lap-three-flooded-shortcut', progress: 0.46, vehicle: 'plane', action: 'auto-switch', radius: 16, active: false },
    ],
    vehicleLocks: [
      { key: 'island-flight-lock', start: 0.58, end: 0.75, vehicle: 'plane' },
    ],
    events: [
      {
        key: 'lap-two-tide-rise',
        trigger: 'lap',
        lap: 2,
        action: 'trigger-hazard',
        hazardType: 'wet',
        duration: 3,
        message: 'Tide rising',
      },
      {
        key: 'lap-three-flood-zone-a',
        trigger: 'lap',
        lap: 3,
        action: 'activate-zone',
        zoneKey: 'lap-three-flooded-ground',
        active: true,
        message: 'Shortcut flooded',
      },
      {
        key: 'lap-three-flood-zone-b',
        trigger: 'lap',
        lap: 3,
        action: 'activate-zone',
        zoneKey: 'lap-three-flooded-shortcut',
        active: true,
      },
      {
        key: 'boat-traffic-loop',
        trigger: 'time',
        repeatInterval: 18,
        action: 'trigger-hazard',
        hazardType: 'boatTraffic',
        duration: 3,
        message: 'Boat traffic',
      },
    ],
    shortcuts: [
      {
        key: 'pier-jump',
        name: 'Pier Jump',
        condition: 'fullSpeedBoost',
        width: 46,
        accent: '#ffbf6b',
        points: [
          { x: 724, y: 620 },
          { x: 806, y: 516 },
          { x: 782, y: 388 },
          { x: 650, y: 338 },
        ],
      },
    ],
    hazards: [
      { key: 'market-fish-cart-a', type: 'fishCart', progress: 0.17, side: -4, radius: 10, cycle: 3.8, openStart: 0.18, openEnd: 0.38, force: 18 },
      { key: 'market-laundry', type: 'laundry', progress: 0.27, side: 2, radius: 12, effect: 'blind', duration: 1.8 },
      { key: 'lighthouse-beam', type: 'lighthouseBeam', progress: 0.43, layer: 'air', side: 8, radius: 14, cycle: 5.4, openStart: 0.22, openEnd: 0.4, effect: 'blind', duration: 3 },
      { key: 'harbor-seagulls', type: 'seagulls', progress: 0.61, layer: 'air', side: 0, radius: 13, cycle: 9.5, openStart: 0.52, openEnd: 0.68, effect: 'spin' },
      { key: 'beach-crab-traps', type: 'crabTrap', progress: 0.84, side: -7, radius: 11, effect: 'slow' },
      { key: 'pier-boat-traffic', type: 'boatTraffic', progress: 0.72, side: 0, radius: 16, cycle: 18, openStart: 0.12, openEnd: 0.25, effect: 'knock-back', force: 28 },
      { key: 'rising-tide-water', type: 'wet', progress: 0.36, side: 6, radius: 18, active: false, effect: 'slow' },
    ],
    scenery: [
      { kind: 'lighthouse', x: 828, y: 168, w: 72, h: 178, color: '#fff4d6' },
      { kind: 'boats', x: 704, y: 534, w: 180, h: 82, color: '#2cc8ff' },
      { kind: 'market', x: 246, y: 286, w: 186, h: 118, color: '#f28b2e' },
      { kind: 'island', x: 794, y: 632, w: 142, h: 92, color: '#2e7d72' },
    ],
    points: [
      { x: 146, y: 584 },
      { x: 116, y: 438 },
      { x: 220, y: 292 },
      { x: 420, y: 206 },
      { x: 598, y: 284 },
      { x: 474, y: 414 },
      { x: 644, y: 528 },
      { x: 850, y: 430 },
      { x: 912, y: 238 },
      { x: 758, y: 156 },
      { x: 600, y: 282 },
      { x: 704, y: 638 },
      { x: 430, y: 658 },
    ],
    aiRivals: [
      { name: 'Captain Brine', color: '#276d8f', accent: '#ffbf6b', lane: 0.2, lineOffset: -8, aggression: 0.32, risk: 0.46, patience: 0.78, signature: 'dock-bell' },
      { name: 'Marina', color: '#65c487', accent: '#2cc8ff', lane: 1.3, lineOffset: 10, aggression: 0.24, risk: 0.42, patience: 0.82 },
      { name: 'Skipper', color: '#e2554f', accent: '#ffd34f', lane: 2.4, lineOffset: -14, aggression: 0.28, risk: 0.5, patience: 0.68 },
    ],
  },
  {
    key: 'static-storm-plateau',
    name: 'Static Storm Plateau',
    shortName: 'Storm Plateau',
    discipline: 'Air Mastery',
    difficulty: 'Expert',
    difficultyWhy: 'Dense hazards, lightning rhythm, route degradation, and switch-lock zones require precise vehicle planning.',
    laps: 3,
    width: 92,
    bananaCount: 10,
    bananaPlacements: [
      { progress: 0.05, side: -0.12 },
      { progress: 0.13, side: 0.14 },
      { progress: 0.23, side: -0.18 },
      { progress: 0.33, side: 0.18 },
      { progress: 0.43, side: -0.12 },
      { progress: 0.53, side: 0.2 },
      { progress: 0.63, side: -0.18 },
      { progress: 0.73, side: 0.18 },
      { progress: 0.83, side: -0.14 },
      { progress: 0.93, side: 0.16 },
    ],
    startProgress: 0.74,
    raceStyle: 'chaotic',
    accent: '#a78bfa',
    asphalt: '#36344f',
    curbA: '#e7f4ff',
    curbB: '#a78bfa',
    grass: '#2d335e',
    hazard: '#6d36d8',
    sky: '#10122f',
    theme: {
      atmosphere: 'Floating mesa islands above a thunderstorm, with charged air and broken rope bridges between cliff edges.',
      time: 'Storm night',
      weather: 'High wind, electric crackle, and constant lightning below the route',
      music: 'Tense percussive rhythm with thunder hits locked to the lightning beat',
    },
    layout: {
      philosophy: 'Reward mastery of air control and hazard timing.',
      shape: 'Scattered mesa islands around a central storm-eye spire.',
      keyTurns: ['Broken rope bridge hop', 'Lightning corridor', 'Storm-eye entry'],
      elevation: ['Ground route hops mesa bridges', 'Air route flies a lightning corridor', 'Hybrid route skims tornadoes for boosts'],
      branches: [
        'Ground layer starts safe but loses bridge planks each lap.',
        'Air layer is fastest but has rhythmic lightning and wind gusts.',
        'Hybrid layer threads tornadoes and the storm eye for rare boxes.',
      ],
    },
    landmarks: [
      'Massive central spire marking the storm eye',
      'Three distinct mesa silhouettes',
      'Constant flashing lightning storm below the islands',
    ],
    signatureObstacles: [
      'Lightning bolts strike on a four-beat rhythm and spin out racers caught in the flash.',
      'Tornadoes pull karts off-course but boost planes that skim the edge.',
      'Rope bridges degrade each lap and force plane usage by lap three.',
      'Static charge zones disable switching for five seconds.',
      'Wind gusts shove planes off course while leaving karts alone.',
    ],
    dynamicElements: [
      'Lightning is readable on lap one, faster on lap two, and erratic on lap three.',
      'Bridge cracks appear before bridge-collapse hazards activate.',
      'Static charge zones can be deliberately triggered by Volt when you follow too closely.',
    ],
    riskRewardShortcut: {
      name: 'Storm Eye',
      summary: 'A direct flight through the central storm eye saves major time, but a lightning strike is guaranteed unless protected by timing, invincibility, or Lightning Rod.',
    },
    powerUpIntel: {
      placement: 'Four boxes sit on ground bridges, six sit in tight air-route gaps, and three rare boxes sit in the storm eye.',
      signatureUse: 'Lightning Rod redirects the next storm strike away from the user and into the current leader.',
      defensive: 'Before lightning corridor and storm-eye entry.',
      aggressive: 'Before static charge zones where rivals are locked into bad vehicles.',
    },
    aiIntel: {
      line: 'Aggressive AI prefers the air route even when lightning timing is risky.',
      shortcuts: 'Volt takes Storm Eye with protection; safer rivals bail to the bridge route.',
      items: 'Two rivals coordinate Bubble Trap and contact pressure at bridge chokepoints.',
      signatureMove: 'Volt deliberately drives through static charge zones to lock the player following close behind.',
    },
    signatureItem: {
      key: 'lightningRod',
      name: 'Lightning Rod',
      summary: 'Self-use protection that redirects the next storm strike to the current leader for eight seconds.',
      color: '#a78bfa',
    },
    boostPads: [0.12, 0.37, 0.61, 0.86],
    itemBoxes: [0.18, 0.34, 0.52, 0.7],
    layers: {
      ground: {
        name: 'Rope bridge route',
        vehiclePreference: 'kart',
        aiWeight: 0.72,
        lineOffset: -0.14,
        itemBoxes: [
          { progress: 0.12, side: -0.2 },
          { progress: 0.26, side: 0.18 },
          { progress: 0.48, side: -0.18 },
          { progress: 0.82, side: 0.2 },
        ],
      },
      air: {
        name: 'Lightning corridor',
        vehiclePreference: 'plane',
        aiWeight: 1.2,
        lineOffset: 0.46,
        itemBoxes: [
          { progress: 0.16, side: 0.3 },
          { progress: 0.28, side: 0.34 },
          { progress: 0.4, side: 0.28 },
          { progress: 0.58, side: 0.36 },
          { progress: 0.74, side: 0.3 },
          { progress: 0.9, side: 0.34 },
        ],
      },
      hybrid: {
        name: 'Storm eye route',
        vehiclePreference: 'plane',
        aiWeight: 1.06,
        lineOffset: -0.38,
        itemBoxes: [
          { progress: 0.45, side: -0.36, rare: true, pool: ['lightningRod', 'invincibility', 'boost'] },
          { progress: 0.5, side: -0.34, rare: true, pool: ['lightningRod', 'ghostReplay', 'bananaMagnet'] },
          { progress: 0.55, side: -0.36, rare: true, pool: ['lightningRod', 'switchBolt', 'bubbleTrap'] },
        ],
      },
    },
    switchPads: [
      { key: 'bridge-plane-pad', progress: 0.31, targetVehicle: 'plane', layer: 'air', radius: 8 },
      { key: 'mesa-kart-pad', progress: 0.68, targetVehicle: 'kart', layer: 'ground', radius: 8 },
      { key: 'storm-eye-plane-pad', progress: 0.43, targetVehicle: 'plane', layer: 'hybrid', radius: 9 },
    ],
    vehicleZones: [
      { key: 'lightning-corridor-plane-only', progress: 0.36, vehicle: 'plane', action: 'auto-switch', radius: 20 },
      { key: 'static-charge-zone-a', progress: 0.58, vehicle: 'plane', action: 'penalty', radius: 16, severity: 0.5 },
      { key: 'lap-three-collapsed-bridge', progress: 0.24, vehicle: 'plane', action: 'auto-switch', radius: 18, active: false },
    ],
    vehicleLocks: [
      { key: 'static-charge-lock', start: 0.54, end: 0.62, vehicle: 'plane' },
      { key: 'storm-eye-lock', start: 0.43, end: 0.56, vehicle: 'plane' },
    ],
    events: [
      {
        key: 'lap-two-lightning-fast',
        trigger: 'lap',
        lap: 2,
        action: 'trigger-hazard',
        hazardType: 'lightning',
        duration: 3.2,
        message: 'Lightning faster',
      },
      {
        key: 'lap-three-bridge-collapse',
        trigger: 'lap',
        lap: 3,
        action: 'activate-zone',
        zoneKey: 'lap-three-collapsed-bridge',
        active: true,
        message: 'Bridge collapsed',
      },
      {
        key: 'storm-eye-strike-loop',
        trigger: 'time',
        repeatInterval: 12,
        action: 'trigger-hazard',
        hazardType: 'lightning',
        duration: 1.6,
        message: 'Storm strike',
      },
    ],
    shortcuts: [
      {
        key: 'storm-eye',
        name: 'Storm Eye',
        condition: 'perfectTimingOrProtection',
        width: 42,
        accent: '#a78bfa',
        points: [
          { x: 440, y: 386 },
          { x: 512, y: 324 },
          { x: 590, y: 386 },
          { x: 512, y: 460 },
        ],
      },
    ],
    hazards: [
      { key: 'lightning-beat-a', type: 'lightning', progress: 0.22, layer: 'air', side: 8, radius: 13, cycle: 4, openStart: 0.1, openEnd: 0.22, effect: 'spin', severity: 1.05 },
      { key: 'lightning-beat-b', type: 'lightning', progress: 0.5, layer: 'hybrid', side: -2, radius: 16, cycle: 4, phase: 0.5, openStart: 0.1, openEnd: 0.22, effect: 'spin', severity: 1.15 },
      { key: 'lightning-beat-c', type: 'lightning', progress: 0.78, layer: 'air', side: 10, radius: 13, cycle: 3.2, phase: 0.25, openStart: 0.1, openEnd: 0.25, effect: 'spin', severity: 1.05 },
      { key: 'tornado-skim-a', type: 'tornado', progress: 0.42, layer: 'hybrid', side: -8, radius: 17, effect: 'pull', force: 26 },
      { key: 'tornado-skim-b', type: 'tornado', progress: 0.64, layer: 'hybrid', side: -10, radius: 17, effect: 'pull', force: 24 },
      { key: 'bridge-cracks-a', type: 'bridgeCollapse', progress: 0.25, layer: 'ground', side: 0, radius: 14, active: false, targetVehicle: 'plane', effect: 'force-switch' },
      { key: 'static-charge-a', type: 'staticCharge', progress: 0.58, layer: 'ground', side: 0, radius: 15, effect: 'switch-lock', duration: 5 },
      { key: 'wind-gust-a', type: 'windGust', progress: 0.72, layer: 'air', side: 8, radius: 18, cycle: 5.6, openStart: 0.3, openEnd: 0.56, effect: 'knock-back', force: 30 },
    ],
    scenery: [
      { kind: 'spire', x: 512, y: 384, w: 102, h: 240, color: '#a78bfa' },
      { kind: 'mesa', x: 226, y: 216, w: 190, h: 110, color: '#4f46e5' },
      { kind: 'mesa', x: 820, y: 258, w: 204, h: 120, color: '#5b4bd8' },
      { kind: 'storm', x: 520, y: 650, w: 500, h: 160, color: '#6d36d8' },
    ],
    points: [
      { x: 132, y: 524 },
      { x: 188, y: 286 },
      { x: 344, y: 142 },
      { x: 526, y: 186 },
      { x: 684, y: 112 },
      { x: 884, y: 248 },
      { x: 782, y: 420 },
      { x: 914, y: 596 },
      { x: 654, y: 668 },
      { x: 512, y: 534 },
      { x: 306, y: 658 },
    ],
    aiRivals: [
      { name: 'Volt', color: '#7c3aed', accent: '#f7fbff', lane: 0.15, lineOffset: 18, aggression: 0.86, risk: 0.92, patience: 0.24, signature: 'static-bait' },
      { name: 'Surge', color: '#2cc8ff', accent: '#ffd34f', lane: 1.35, lineOffset: -16, aggression: 0.74, risk: 0.84, patience: 0.3 },
      { name: 'Nimbus', color: '#374151', accent: '#a78bfa', lane: 2.55, lineOffset: 4, aggression: 0.68, risk: 0.76, patience: 0.38 },
    ],
  },
  {
    key: 'orbital-relay',
    name: 'Orbital Relay',
    shortName: 'Relay',
    discipline: 'Puzzle',
    difficulty: 'Expert',
    difficultyWhy: 'The fastest lap comes from reading gate phases, conveyors, and airlock timing before committing.',
    laps: 3,
    width: 90,
    startProgress: 0.765,
    raceStyle: 'puzzle',
    accent: '#9bff7a',
    asphalt: '#2d3448',
    curbA: '#f7fbff',
    curbB: '#9bff7a',
    grass: '#111827',
    hazard: '#4a3178',
    sky: '#050813',
    theme: {
      atmosphere: 'A rotating cargo ring around a gravity-shifting relay station above a storm planet.',
      time: 'Perpetual orbital night',
      weather: 'Hard vacuum outside, cold station light inside',
      music: 'Minimal techno with warning chimes and sub-bass gravity drops',
    },
    layout: {
      philosophy: 'Timing and observation',
      shape: 'A segmented station loop with two magnetic conveyors, timed laser gates, and an airlock bypass.',
      keyTurns: ['Docking-ring corkscrew', 'Cargo-bay switchback', 'Green-phase airlock entry'],
      elevation: ['Gravity plates simulate downhill speed boosts', 'Docking lifts alter traction in timed waves'],
      branches: ['Airlock Skip is fastest only during the green phase or while Phase Key is active'],
    },
    signatureObstacles: [
      'Laser shutters close on a schedule and punish drivers who enter late.',
      'Magnetic conveyors pull karts into alternate lines and can set up boosts or crashes.',
      'Gravity wells invert steering feel by pushing the kart sideways through corners.',
      'Docking drones sweep across item boxes and temporarily block greedy pickups.',
    ],
    dynamicElements: [
      'Green, amber, and red phase lights change every few seconds.',
      'Conveyor direction flips each lap.',
      'The Airlock Skip opens only during green phase unless a Phase Key overrides it.',
    ],
    riskRewardShortcut: {
      name: 'Airlock Skip',
      summary: 'A straight shot through a pressure door. Enter during green phase to gain time; enter on red and the shutter kills speed.',
    },
    powerUpIntel: {
      placement: 'Defensive/setup boxes sit before gates; aggressive boxes sit after conveyors, where rivals are lined up.',
      signatureUse: 'Phase Key opens shutters, stabilizes magnetic pull, and guarantees the Airlock Skip.',
      defensive: 'Before laser shutters to protect planned timing.',
      aggressive: 'After magnetic conveyors, where rockets have predictable targets.',
    },
    aiIntel: {
      line: 'CPU racers hesitate before red gates and accelerate hard on green.',
      shortcuts: 'Apex takes Airlock Skip only on green or with Phase Key; Forge usually refuses the puzzle route.',
      items: 'Rivals save shields and Phase Key rather than using items immediately.',
      signatureMove: 'Apex waits half a beat, pops Phase Key, and cuts the Airlock while impatient racers hit the shutter.',
    },
    signatureItem: {
      key: 'phaseKey',
      name: 'Phase Key',
      summary: 'Forces gates open, dampens magnetic pull, and gives a controlled station boost.',
      color: '#9bff7a',
    },
    boostPads: [0.12, 0.49, 0.735],
    itemBoxes: [0.255, 0.565, 0.88],
    layers: {
      ground: {
        name: 'Cargo ring',
        vehiclePreference: 'kart',
        aiWeight: 0.94,
        lineOffset: -0.12,
        itemBoxes: [
          { progress: 0.255, side: -0.18 },
          { progress: 0.565, side: 0.2 },
        ],
      },
      air: {
        name: 'Relay arc',
        vehiclePreference: 'plane',
        aiWeight: 0.96,
        lineOffset: 0.46,
        itemBoxes: [{ progress: 0.74, side: 0.26, rare: true }],
      },
      hybrid: {
        name: 'Airlock skip',
        vehiclePreference: 'hover',
        aiWeight: 1.06,
        lineOffset: -0.36,
        itemBoxes: [{ progress: 0.88, side: -0.22 }],
      },
    },
    switchPads: [
      { key: 'relay-plane-pad', progress: 0.18, targetVehicle: 'plane', layer: 'air', radius: 8 },
      { key: 'relay-hover-pad', progress: 0.66, targetVehicle: 'hover', layer: 'hybrid', radius: 8 },
    ],
    vehicleZones: [
      { key: 'green-airlock-only', progress: 0.66, vehicle: 'hover', action: 'auto-switch', radius: 16 },
    ],
    vehicleLocks: [
      { key: 'airlock-vehicle-lock', start: 0.62, end: 0.72, vehicle: 'hover' },
    ],
    events: [
      {
        key: 'phase-shutter-pulse',
        trigger: 'position',
        progress: 0.66,
        action: 'trigger-hazard',
        hazardType: 'laser',
        duration: 2,
        message: 'Shutters cycling',
      },
    ],
    shortcuts: [
      {
        key: 'airlock-skip',
        name: 'Airlock Skip',
        condition: 'phaseGreen',
        width: 50,
        accent: '#9bff7a',
        points: [
          { x: 286, y: 292 },
          { x: 430, y: 272 },
          { x: 584, y: 292 },
          { x: 718, y: 384 },
        ],
      },
    ],
    hazards: [
      { type: 'laser', progress: 0.22, side: 0, radius: 48, cycle: 5.8, openStart: 0.16, openEnd: 0.54 },
      { type: 'conveyor', progress: 0.36, side: 12, radius: 72, cycle: 4.4, force: 75 },
      { type: 'gravity', progress: 0.51, side: -12, radius: 80, cycle: 6.2, openStart: 0.48, openEnd: 0.84, force: 68 },
      { type: 'laser', progress: 0.66, side: 0, radius: 50, cycle: 6.2, openStart: 0.58, openEnd: 0.9 },
      { type: 'conveyor', progress: 0.83, side: -8, radius: 70, cycle: 4.8, force: -72 },
    ],
    scenery: [
      { kind: 'planet', x: 832, y: 132, r: 92, color: '#4f8cff' },
      { kind: 'station', x: 512, y: 390, w: 350, h: 190, color: '#40516f' },
      { kind: 'solar', x: 120, y: 144, w: 190, h: 52, color: '#9bff7a' },
      { kind: 'solar', x: 742, y: 604, w: 196, h: 52, color: '#9bff7a' },
    ],
    points: [
      { x: 148, y: 474 },
      { x: 222, y: 268 },
      { x: 430, y: 150 },
      { x: 622, y: 150 },
      { x: 800, y: 276 },
      { x: 846, y: 492 },
      { x: 680, y: 632 },
      { x: 464, y: 614 },
      { x: 304, y: 522 },
    ],
    aiRivals: [
      { name: 'Apex', color: '#f3ece0', accent: '#f45b69', lane: 0.15, lineOffset: -6, aggression: 0.28, risk: 0.64, patience: 0.9, signature: 'phase-airlock' },
      { name: 'Rift', color: '#9b5de5', accent: '#2ec4b6', lane: 1.35, lineOffset: -18, aggression: 0.42, risk: 0.62, patience: 0.72 },
      { name: 'Forge', color: '#e2554f', accent: '#ffd34f', lane: 2.55, lineOffset: 18, aggression: 0.48, risk: 0.32, patience: 0.62 },
    ],
  },
];
