export const RACE_TRACKS = [
  {
    key: 'comeback-city',
    name: 'Comeback City Grand Prix',
    shortName: 'Comeback City',
    discipline: 'City Branching',
    difficulty: 'Standard',
    difficultyWhy: 'Wide boulevards, readable forks, and forgiving off-road shoulders let players practice drifting without corridor walls.',
    laps: 3,
    width: 150,
    bananaCount: 18,
    bananaPlacements: [
      { progress: 0.045, side: -0.18 },
      { progress: 0.105, side: 0.18 },
      { progress: 0.165, side: -0.08 },
      { progress: 0.225, side: 0.22 },
      { progress: 0.285, side: -0.2 },
      { progress: 0.345, side: 0.12 },
      { progress: 0.405, side: -0.18 },
      { progress: 0.465, side: 0.22 },
      { progress: 0.525, side: -0.1 },
      { progress: 0.585, side: 0.16 },
      { progress: 0.645, side: -0.2 },
      { progress: 0.705, side: 0.12 },
      { progress: 0.765, side: -0.16 },
      { progress: 0.825, side: 0.2 },
      { progress: 0.875, side: -0.14 },
      { progress: 0.925, side: 0.18 },
      { progress: 0.965, side: -0.08 },
      { progress: 0.99, side: 0.12 },
    ],
    startProgress: 0.815,
    raceStyle: 'technical',
    accent: '#46d9ef',
    asphalt: '#454c56',
    curbA: '#f7fbff',
    curbB: '#46d9ef',
    grass: '#57ac63',
    hazard: '#ff5b68',
    sky: '#66c8ed',
    theme: {
      atmosphere: 'Bright arcade city with district portals, split boulevards, plaza shortcuts, water edges, and mountain skyline.',
      time: 'Clear afternoon',
      weather: 'Clean visibility with moving cloud shadows',
      music: 'Punchy arcade brass, city percussion, and boost stingers',
    },
    layout: {
      philosophy: 'Make the route feel like a full city map instead of a narrow prototype track.',
      shape: 'A large boulevard loop wrapping a central plaza, food market, lab bridge, waterfront, and garage approach.',
      keyTurns: ['Gym plaza sweeper', 'Food-court fork', 'Lab bridge S-turn', 'Garage roundabout'],
      elevation: ['Ground road stays wide', 'Air route clears the lab bridge', 'Hybrid route cuts through the waterfront plaza'],
      branches: [
        'Food Court shortcut cuts inside the orange market.',
        'Lab bridge split crosses over the central boulevard.',
        'Garage waterfront branch reconnects before the finish plaza.',
      ],
    },
    landmarks: [
      'Five glowing district portals built as 3D geometry',
      'Central cyan objective tower',
      'Waterfront bridge and plaza loop',
      'Chunky skyline, mountains, trees, shopfronts, and route signs',
    ],
    signatureObstacles: [
      'Crosswalk pulse zones punish careless straight-lining.',
      'Clinic wet clean-up strips slow karts on the inside lane.',
      'Lab laser gates encourage route switching.',
      'Garage mine carts cross a branch on a timer.',
    ],
    dynamicElements: [
      'District signs brighten as racers approach.',
      'Lab bridge hazards pulse on an alternating rhythm.',
      'Garage branch opens as a high-speed drift reward.',
    ],
    riskRewardShortcut: {
      name: 'Food Court Cut',
      summary: 'A broad inside lane through awnings and stalls. It is faster when drifted cleanly, but wet strips punish sloppy exits.',
    },
    powerUpIntel: {
      placement: 'Boxes sit across the main boulevard, branch entries, lab bridge, and waterfront exit so each route has a visible reward.',
      signatureUse: 'City Turbo gives a clean boost for long drifts and branch exits.',
      defensive: 'Before the lab bridge and garage reconnect.',
      aggressive: 'At the food-court fork and clinic plaza.',
    },
    aiIntel: {
      line: 'Default rivals favor the wide main boulevard.',
      shortcuts: 'Riskier rivals choose the food and garage branches after lap one.',
      items: 'Boost and switch items appear before major route choices.',
      signatureMove: 'Rivals fire City Turbo after long plaza drifts.',
    },
    signatureItem: {
      key: 'boost',
      name: 'City Turbo',
      summary: 'Universal boost tuned for long boulevard drifts and branch exits.',
      color: '#46d9ef',
    },
    boostPads: [0.07, 0.245, 0.475, 0.68, 0.87],
    itemBoxes: [0.08, 0.17, 0.29, 0.42, 0.58, 0.72, 0.84, 0.94],
    layers: {
      ground: {
        name: 'Main boulevard',
        vehiclePreference: 'kart',
        aiWeight: 1.18,
        lineOffset: 0,
        itemBoxes: [
          { progress: 0.08, side: -0.22 },
          { progress: 0.17, side: 0.2 },
          { progress: 0.29, side: -0.18 },
          { progress: 0.42, side: 0.16 },
          { progress: 0.58, side: -0.2 },
          { progress: 0.72, side: 0.22 },
          { progress: 0.84, side: -0.16 },
          { progress: 0.94, side: 0.18 },
        ],
      },
      air: {
        name: 'Lab bridge air line',
        vehiclePreference: 'plane',
        aiWeight: 0.92,
        lineOffset: 0.42,
        itemBoxes: [
          { progress: 0.22, side: 0.34 },
          { progress: 0.39, side: 0.3 },
          { progress: 0.61, side: 0.36 },
          { progress: 0.79, side: 0.32 },
        ],
      },
      hybrid: {
        name: 'Waterfront branch',
        vehiclePreference: 'hover',
        aiWeight: 1.02,
        lineOffset: -0.38,
        itemBoxes: [
          { progress: 0.34, side: -0.34, rare: true, pool: ['boost', 'ghostReplay', 'bananaMagnet'] },
          { progress: 0.66, side: -0.36, rare: true, pool: ['boost', 'invincibility', 'switchBolt'] },
          { progress: 0.9, side: -0.32, rare: true, pool: ['boost', 'decoyCrate', 'hazardBell'] },
        ],
      },
    },
    switchPads: [
      { key: 'city-lab-plane-pad', progress: 0.23, targetVehicle: 'plane', layer: 'air', radius: 10 },
      { key: 'city-waterfront-hover-pad', progress: 0.56, targetVehicle: 'hover', layer: 'hybrid', radius: 10 },
      { key: 'city-finish-kart-pad', progress: 0.86, targetVehicle: 'kart', layer: 'ground', radius: 10 },
    ],
    vehicleZones: [
      { key: 'city-lab-air-lane', progress: 0.37, vehicle: 'plane', action: 'auto-switch', radius: 22 },
      { key: 'city-waterfront-hover-lane', progress: 0.64, vehicle: 'hover', action: 'auto-switch', radius: 20 },
      { key: 'city-gym-kart-plaza', progress: 0.9, vehicle: 'kart', action: 'auto-switch', radius: 18 },
    ],
    vehicleLocks: [
      { key: 'city-lab-bridge-lock', start: 0.31, end: 0.44, vehicle: 'plane' },
      { key: 'city-waterfront-lock', start: 0.58, end: 0.71, vehicle: 'hover' },
    ],
    events: [
      {
        key: 'city-lap-two-lab-lights',
        trigger: 'lap',
        lap: 2,
        action: 'trigger-hazard',
        hazardType: 'laser',
        duration: 3,
        message: 'Lab lights',
      },
      {
        key: 'city-garage-mine-cart',
        trigger: 'time',
        repeatInterval: 14,
        action: 'trigger-hazard',
        hazardType: 'mineCart',
        duration: 2.8,
        message: 'Garage crossing',
      },
    ],
    shortcuts: [
      {
        key: 'food-court-cut',
        name: 'Food Court Cut',
        width: 96,
        startProgress: 0.11,
        endProgress: 0.24,
        points: [
          { x: 222, y: 578 },
          { x: 310, y: 500 },
          { x: 374, y: 406 },
          { x: 452, y: 296 },
        ],
      },
      {
        key: 'lab-bridge-split',
        name: 'Lab Bridge Split',
        width: 88,
        startProgress: 0.32,
        endProgress: 0.48,
        points: [
          { x: 544, y: 210 },
          { x: 636, y: 298 },
          { x: 660, y: 420 },
          { x: 596, y: 538 },
        ],
      },
      {
        key: 'garage-waterfront-branch',
        name: 'Garage Waterfront Branch',
        width: 104,
        startProgress: 0.61,
        endProgress: 0.78,
        points: [
          { x: 832, y: 440 },
          { x: 790, y: 560 },
          { x: 660, y: 642 },
          { x: 504, y: 646 },
        ],
      },
      {
        key: 'central-plaza-loop',
        name: 'Central Plaza Loop',
        width: 92,
        startProgress: 0.78,
        endProgress: 0.92,
        points: [
          { x: 504, y: 646 },
          { x: 432, y: 552 },
          { x: 486, y: 456 },
          { x: 620, y: 432 },
          { x: 704, y: 512 },
        ],
      },
    ],
    hazards: [
      { key: 'city-food-wet-strip', type: 'wet', progress: 0.18, side: -6, radius: 15, effect: 'slow' },
      { key: 'city-crosswalk-pulse', type: 'pulseZone', progress: 0.28, side: 3, radius: 17, cycle: 5.2, openStart: 0.18, openEnd: 0.52, effect: 'control-flip' },
      { key: 'city-lab-laser', type: 'laser', progress: 0.39, layer: 'air', side: 6, radius: 15, cycle: 4.7, openStart: 0.2, openEnd: 0.38, effect: 'spin' },
      { key: 'city-waterfront-wet', type: 'wet', progress: 0.61, side: -8, radius: 18, effect: 'slow' },
      { key: 'city-garage-cart', type: 'mineCart', progress: 0.73, side: 0, radius: 17, cycle: 6.3, openStart: 0.25, openEnd: 0.46, effect: 'knock-back' },
      { key: 'city-clinic-gate', type: 'gate', progress: 0.88, side: 5, radius: 16, cycle: 5.8, openStart: 0.12, openEnd: 0.4, effect: 'spin' },
    ],
    scenery: [
      { kind: 'market', x: 318, y: 476, w: 210, h: 118, color: '#ffac32' },
      { kind: 'spire', x: 642, y: 312, w: 120, h: 170, color: '#d45cff' },
      { kind: 'boats', x: 806, y: 592, w: 190, h: 92, color: '#46d9ef' },
      { kind: 'rails', x: 720, y: 482, w: 170, h: 70, color: '#2cc8ff' },
      { kind: 'drill', x: 884, y: 360, w: 92, h: 130, color: '#2cc8ff' },
    ],
    points: [
      { x: 178, y: 610 },
      { x: 132, y: 470 },
      { x: 192, y: 326 },
      { x: 354, y: 212 },
      { x: 548, y: 176 },
      { x: 742, y: 248 },
      { x: 872, y: 388 },
      { x: 840, y: 548 },
      { x: 704, y: 654 },
      { x: 512, y: 690 },
      { x: 362, y: 620 },
      { x: 438, y: 490 },
      { x: 608, y: 430 },
      { x: 500, y: 308 },
      { x: 314, y: 374 },
      { x: 250, y: 526 },
    ],
    aiRivals: [
      { name: 'Coach Volt', color: '#ef4334', accent: '#46d9ef', lane: 0.2, lineOffset: -8, aggression: 0.36, risk: 0.52, patience: 0.72, signature: 'city-turbo' },
      { name: 'Chef Flash', color: '#f28b2e', accent: '#ffd34f', lane: 1.2, lineOffset: 12, aggression: 0.28, risk: 0.58, patience: 0.7 },
      { name: 'Dr. Apex', color: '#8a53df', accent: '#80ff62', lane: 2.1, lineOffset: -14, aggression: 0.31, risk: 0.48, patience: 0.76 },
    ],
  },
  {
    key: 'tide-pier',
    name: 'Tide Pier',
    shortName: 'Tide Pier',
    discipline: 'Switching',
    difficulty: 'Beginner',
    difficultyWhy: 'Forgiving turns, clear route identity, and low hazard density teach when to switch between kart and plane.',
    laps: 3,
    width: 96,
    bananaCount: 10,
    bananaPlacements: [
      { progress: 0.06, side: -0.16 },
      { progress: 0.14, side: 0.12 },
      { progress: 0.24, side: -0.18 },
      { progress: 0.34, side: 0.16 },
      { progress: 0.44, side: -0.1 },
      { progress: 0.54, side: 0.18 },
      { progress: 0.64, side: -0.16 },
      { progress: 0.74, side: 0.14 },
      { progress: 0.84, side: -0.12 },
      { progress: 0.94, side: 0.16 },
    ],
    startProgress: 0.82,
    raceStyle: 'technical',
    accent: '#ffbf6b',
    asphalt: '#6f6656',
    curbA: '#fff4d6',
    curbB: '#2cc8ff',
    grass: '#2e7d72',
    hazard: '#0b5f7a',
    sky: '#f6a35f',
    theme: {
      atmosphere: 'Working coastal pier town with fishing boats, market stalls, rope piles, gulls, and drying laundry.',
      time: 'Golden hour',
      weather: 'Warm salt air, soft spray, and a rising tide by lap three',
      music: 'Relaxed island groove that builds with gull cries and distant boat horns',
    },
    layout: {
      philosophy: 'Teach vehicle switching without punishing experimentation.',
      shape: 'A figure-8 coastal route with a bridge crossing, a narrow fish market, a pier launch, and a beach return.',
      keyTurns: ['Fish-market S-bend', 'Lighthouse base loop', 'Beach landing bend'],
      elevation: ['Ground route crosses under the pier', 'Air route rises over the harbor', 'Hybrid route launches to the island and returns to the beach'],
      branches: [
        'Ground layer is safest through town.',
        'Air layer clears harbor hazards but must dodge lighthouse beam and gulls.',
        'Hybrid layer uses the pier ramp to reach the island rare boxes.',
      ],
    },
    landmarks: [
      'Massive lighthouse visible from anywhere on the track',
      'Fishing pier with bobbing boats',
      'Cliffside fish market',
      'Distant island halfway point for the hybrid route',
    ],
    signatureObstacles: [
      'Sliding fish carts push karts off the racing line on a readable timer.',
      'Hanging laundry briefly obscures vision through the fish market.',
      'The rotating lighthouse beam blinds plane racers in its arc for three seconds.',
      'Seagull flocks disperse on contact but cause a spin-out.',
      'Crab traps slow karts that clip the inside of beach turns.',
    ],
    dynamicElements: [
      'Rising tide expands water hazards each lap and activates flooded shortcut zones by lap three.',
      'Boat traffic crosses under the pier on a timer and blocks the low shortcut.',
      'Captain Brine can ring the dock bell to summon seagulls early while in second place.',
    ],
    riskRewardShortcut: {
      name: 'Pier Jump',
      summary: 'A boost-speed jump off the end of the pier toward the harbor line. Hit it cleanly for a faster crossing; miss it and the reset costs about four seconds.',
    },
    powerUpIntel: {
      placement: 'Six ground boxes split between safe market exits and risky inside lines, four air boxes in lighthouse and gull gaps, and two rare boxes on the hybrid island path.',
      signatureUse: 'Anchor Drop protects narrow alley entrances by dragging a kart backward when it drives over the embedded anchor.',
      defensive: 'At fish-market entry, lighthouse base, and beach landing.',
      aggressive: 'Before the pier jump and the air-route lighthouse gap.',
    },
    aiIntel: {
      line: 'Default racing line stays on the ground route.',
      shortcuts: 'Rivals switch to plane on lap two if the rising tide blocks the shortcut.',
      items: 'Anchor Drop is used defensively at market and alley entrances.',
      signatureMove: 'Captain Brine rings the dock bell to summon seagulls early when he is in second place.',
    },
    signatureItem: {
      key: 'anchorDrop',
      name: 'Anchor Drop',
      summary: 'Kart-only trap that sinks into the road and drags the next opponent backward three meters.',
      color: '#38506b',
    },
    boostPads: [0.095, 0.585, 0.742],
    itemBoxes: [0.08, 0.18, 0.32, 0.48, 0.68, 0.88],
    layers: {
      ground: {
        name: 'Fish-market ground line',
        vehiclePreference: 'kart',
        aiWeight: 1.14,
        lineOffset: -0.08,
        itemBoxes: [
          { progress: 0.08, side: -0.22 },
          { progress: 0.18, side: 0.18 },
          { progress: 0.32, side: -0.26 },
          { progress: 0.48, side: 0.2 },
          { progress: 0.68, side: -0.2 },
          { progress: 0.88, side: 0.22 },
        ],
      },
      air: {
        name: 'Harbor air line',
        vehiclePreference: 'plane',
        aiWeight: 0.88,
        lineOffset: 0.44,
        itemBoxes: [
          { progress: 0.21, side: 0.3 },
          { progress: 0.39, side: 0.34 },
          { progress: 0.57, side: 0.3 },
          { progress: 0.79, side: 0.32 },
        ],
      },
      hybrid: {
        name: 'Island launch route',
        vehiclePreference: 'hover',
        aiWeight: 0.98,
        lineOffset: -0.38,
        itemBoxes: [
          { progress: 0.63, side: -0.36, rare: true, pool: ['anchorDrop', 'invincibility', 'bananaMagnet'] },
          { progress: 0.735, side: -0.34, rare: true, pool: ['anchorDrop', 'ghostReplay', 'boost'] },
        ],
      },
    },
    switchPads: [
      { key: 'pier-launch-plane-pad', progress: 0.585, targetVehicle: 'plane', layer: 'hybrid', radius: 8 },
      { key: 'island-hover-pad', progress: 0.685, targetVehicle: 'hover', layer: 'hybrid', radius: 8 },
      { key: 'beach-landing-kart-pad', progress: 0.76, targetVehicle: 'kart', layer: 'ground', radius: 8 },
      { key: 'lap-three-flood-plane-pad', progress: 0.36, targetVehicle: 'plane', layer: 'air', radius: 9 },
    ],
    vehicleZones: [
      { key: 'fish-market-kart-only', progress: 0.24, vehicle: 'kart', action: 'block', radius: 15 },
      { key: 'harbor-air-only', progress: 0.62, vehicle: 'plane', action: 'auto-switch', radius: 18 },
      { key: 'lap-three-flooded-ground', progress: 0.34, vehicle: 'plane', action: 'auto-switch', radius: 18, active: false },
      { key: 'lap-three-flooded-shortcut', progress: 0.46, vehicle: 'plane', action: 'auto-switch', radius: 16, active: false },
    ],
    vehicleLocks: [
      { key: 'island-flight-lock', start: 0.58, end: 0.75, vehicle: 'plane' },
    ],
    events: [
      {
        key: 'lap-two-tide-rise',
        trigger: 'lap',
        lap: 2,
        action: 'trigger-hazard',
        hazardType: 'wet',
        duration: 3,
        message: 'Tide rising',
      },
      {
        key: 'lap-three-flood-zone-a',
        trigger: 'lap',
        lap: 3,
        action: 'activate-zone',
        zoneKey: 'lap-three-flooded-ground',
        active: true,
        message: 'Shortcut flooded',
      },
      {
        key: 'lap-three-flood-zone-b',
        trigger: 'lap',
        lap: 3,
        action: 'activate-zone',
        zoneKey: 'lap-three-flooded-shortcut',
        active: true,
      },
      {
        key: 'boat-traffic-loop',
        trigger: 'time',
        repeatInterval: 18,
        action: 'trigger-hazard',
        hazardType: 'boatTraffic',
        duration: 3,
        message: 'Boat traffic',
      },
    ],
    shortcuts: [
      {
        key: 'pier-jump',
        name: 'Pier Jump',
        condition: 'fullSpeedBoost',
        width: 46,
        accent: '#ffbf6b',
        points: [
          { x: 724, y: 620 },
          { x: 806, y: 516 },
          { x: 782, y: 388 },
          { x: 650, y: 338 },
        ],
      },
    ],
    hazards: [
      { key: 'market-fish-cart-a', type: 'fishCart', progress: 0.17, side: -4, radius: 10, cycle: 3.8, openStart: 0.18, openEnd: 0.38, force: 18 },
      { key: 'market-laundry', type: 'laundry', progress: 0.27, side: 2, radius: 12, effect: 'blind', duration: 1.8 },
      { key: 'lighthouse-beam', type: 'lighthouseBeam', progress: 0.43, layer: 'air', side: 8, radius: 14, cycle: 5.4, openStart: 0.22, openEnd: 0.4, effect: 'blind', duration: 3 },
      { key: 'harbor-seagulls', type: 'seagulls', progress: 0.61, layer: 'air', side: 0, radius: 13, cycle: 9.5, openStart: 0.52, openEnd: 0.68, effect: 'spin' },
      { key: 'beach-crab-traps', type: 'crabTrap', progress: 0.84, side: -7, radius: 11, effect: 'slow' },
      { key: 'pier-boat-traffic', type: 'boatTraffic', progress: 0.72, side: 0, radius: 16, cycle: 18, openStart: 0.12, openEnd: 0.25, effect: 'knock-back', force: 28 },
      { key: 'rising-tide-water', type: 'wet', progress: 0.36, side: 6, radius: 18, active: false, effect: 'slow' },
    ],
    scenery: [
      { kind: 'lighthouse', x: 828, y: 168, w: 72, h: 178, color: '#fff4d6' },
      { kind: 'boats', x: 704, y: 534, w: 180, h: 82, color: '#2cc8ff' },
      { kind: 'market', x: 246, y: 286, w: 186, h: 118, color: '#f28b2e' },
      { kind: 'island', x: 794, y: 632, w: 142, h: 92, color: '#2e7d72' },
    ],
    points: [
      { x: 146, y: 584 },
      { x: 116, y: 438 },
      { x: 220, y: 292 },
      { x: 420, y: 206 },
      { x: 598, y: 284 },
      { x: 474, y: 414 },
      { x: 644, y: 528 },
      { x: 850, y: 430 },
      { x: 912, y: 238 },
      { x: 758, y: 156 },
      { x: 600, y: 282 },
      { x: 704, y: 638 },
      { x: 430, y: 658 },
    ],
    aiRivals: [
      { name: 'Captain Brine', color: '#276d8f', accent: '#ffbf6b', lane: 0.2, lineOffset: -8, aggression: 0.32, risk: 0.46, patience: 0.78, signature: 'dock-bell' },
      { name: 'Marina', color: '#65c487', accent: '#2cc8ff', lane: 1.3, lineOffset: 10, aggression: 0.24, risk: 0.42, patience: 0.82 },
      { name: 'Skipper', color: '#e2554f', accent: '#ffd34f', lane: 2.4, lineOffset: -14, aggression: 0.28, risk: 0.5, patience: 0.68 },
    ],
  },
  {
    key: 'static-storm-plateau',
    name: 'Static Storm Plateau',
    shortName: 'Storm Plateau',
    discipline: 'Air Mastery',
    difficulty: 'Expert',
    difficultyWhy: 'Dense hazards, lightning rhythm, route degradation, and switch-lock zones require precise vehicle planning.',
    laps: 3,
    width: 92,
    bananaCount: 10,
    bananaPlacements: [
      { progress: 0.05, side: -0.12 },
      { progress: 0.13, side: 0.14 },
      { progress: 0.23, side: -0.18 },
      { progress: 0.33, side: 0.18 },
      { progress: 0.43, side: -0.12 },
      { progress: 0.53, side: 0.2 },
      { progress: 0.63, side: -0.18 },
      { progress: 0.73, side: 0.18 },
      { progress: 0.83, side: -0.14 },
      { progress: 0.93, side: 0.16 },
    ],
    startProgress: 0.74,
    raceStyle: 'chaotic',
    accent: '#a78bfa',
    asphalt: '#36344f',
    curbA: '#e7f4ff',
    curbB: '#a78bfa',
    grass: '#2d335e',
    hazard: '#6d36d8',
    sky: '#10122f',
    theme: {
      atmosphere: 'Floating mesa islands above a thunderstorm, with charged air and broken rope bridges between cliff edges.',
      time: 'Storm night',
      weather: 'High wind, electric crackle, and constant lightning below the route',
      music: 'Tense percussive rhythm with thunder hits locked to the lightning beat',
    },
    layout: {
      philosophy: 'Reward mastery of air control and hazard timing.',
      shape: 'Scattered mesa islands around a central storm-eye spire.',
      keyTurns: ['Broken rope bridge hop', 'Lightning corridor', 'Storm-eye entry'],
      elevation: ['Ground route hops mesa bridges', 'Air route flies a lightning corridor', 'Hybrid route skims tornadoes for boosts'],
      branches: [
        'Ground layer starts safe but loses bridge planks each lap.',
        'Air layer is fastest but has rhythmic lightning and wind gusts.',
        'Hybrid layer threads tornadoes and the storm eye for rare boxes.',
      ],
    },
    landmarks: [
      'Massive central spire marking the storm eye',
      'Three distinct mesa silhouettes',
      'Constant flashing lightning storm below the islands',
    ],
    signatureObstacles: [
      'Lightning bolts strike on a four-beat rhythm and spin out racers caught in the flash.',
      'Tornadoes pull karts off-course but boost planes that skim the edge.',
      'Rope bridges degrade each lap and force plane usage by lap three.',
      'Static charge zones disable switching for five seconds.',
      'Wind gusts shove planes off course while leaving karts alone.',
    ],
    dynamicElements: [
      'Lightning is readable on lap one, faster on lap two, and erratic on lap three.',
      'Bridge cracks appear before bridge-collapse hazards activate.',
      'Static charge zones can be deliberately triggered by Volt when you follow too closely.',
    ],
    riskRewardShortcut: {
      name: 'Storm Eye',
      summary: 'A direct flight through the central storm eye saves major time, but a lightning strike is guaranteed unless protected by timing, invincibility, or Lightning Rod.',
    },
    powerUpIntel: {
      placement: 'Four boxes sit on ground bridges, six sit in tight air-route gaps, and three rare boxes sit in the storm eye.',
      signatureUse: 'Lightning Rod redirects the next storm strike away from the user and into the current leader.',
      defensive: 'Before lightning corridor and storm-eye entry.',
      aggressive: 'Before static charge zones where rivals are locked into bad vehicles.',
    },
    aiIntel: {
      line: 'Aggressive AI prefers the air route even when lightning timing is risky.',
      shortcuts: 'Volt takes Storm Eye with protection; safer rivals bail to the bridge route.',
      items: 'Two rivals coordinate Bubble Trap and contact pressure at bridge chokepoints.',
      signatureMove: 'Volt deliberately drives through static charge zones to lock the player following close behind.',
    },
    signatureItem: {
      key: 'lightningRod',
      name: 'Lightning Rod',
      summary: 'Self-use protection that redirects the next storm strike to the current leader for eight seconds.',
      color: '#a78bfa',
    },
    boostPads: [0.12, 0.37, 0.61, 0.86],
    itemBoxes: [0.18, 0.34, 0.52, 0.7],
    layers: {
      ground: {
        name: 'Rope bridge route',
        vehiclePreference: 'kart',
        aiWeight: 0.72,
        lineOffset: -0.14,
        itemBoxes: [
          { progress: 0.12, side: -0.2 },
          { progress: 0.26, side: 0.18 },
          { progress: 0.48, side: -0.18 },
          { progress: 0.82, side: 0.2 },
        ],
      },
      air: {
        name: 'Lightning corridor',
        vehiclePreference: 'plane',
        aiWeight: 1.2,
        lineOffset: 0.46,
        itemBoxes: [
          { progress: 0.16, side: 0.3 },
          { progress: 0.28, side: 0.34 },
          { progress: 0.4, side: 0.28 },
          { progress: 0.58, side: 0.36 },
          { progress: 0.74, side: 0.3 },
          { progress: 0.9, side: 0.34 },
        ],
      },
      hybrid: {
        name: 'Storm eye route',
        vehiclePreference: 'plane',
        aiWeight: 1.06,
        lineOffset: -0.38,
        itemBoxes: [
          { progress: 0.45, side: -0.36, rare: true, pool: ['lightningRod', 'invincibility', 'boost'] },
          { progress: 0.5, side: -0.34, rare: true, pool: ['lightningRod', 'ghostReplay', 'bananaMagnet'] },
          { progress: 0.55, side: -0.36, rare: true, pool: ['lightningRod', 'switchBolt', 'bubbleTrap'] },
        ],
      },
    },
    switchPads: [
      { key: 'bridge-plane-pad', progress: 0.31, targetVehicle: 'plane', layer: 'air', radius: 8 },
      { key: 'mesa-kart-pad', progress: 0.68, targetVehicle: 'kart', layer: 'ground', radius: 8 },
      { key: 'storm-eye-plane-pad', progress: 0.43, targetVehicle: 'plane', layer: 'hybrid', radius: 9 },
    ],
    vehicleZones: [
      { key: 'lightning-corridor-plane-only', progress: 0.36, vehicle: 'plane', action: 'auto-switch', radius: 20 },
      { key: 'static-charge-zone-a', progress: 0.58, vehicle: 'plane', action: 'penalty', radius: 16, severity: 0.5 },
      { key: 'lap-three-collapsed-bridge', progress: 0.24, vehicle: 'plane', action: 'auto-switch', radius: 18, active: false },
    ],
    vehicleLocks: [
      { key: 'static-charge-lock', start: 0.54, end: 0.62, vehicle: 'plane' },
      { key: 'storm-eye-lock', start: 0.43, end: 0.56, vehicle: 'plane' },
    ],
    events: [
      {
        key: 'lap-two-lightning-fast',
        trigger: 'lap',
        lap: 2,
        action: 'trigger-hazard',
        hazardType: 'lightning',
        duration: 3.2,
        message: 'Lightning faster',
      },
      {
        key: 'lap-three-bridge-collapse',
        trigger: 'lap',
        lap: 3,
        action: 'activate-zone',
        zoneKey: 'lap-three-collapsed-bridge',
        active: true,
        message: 'Bridge collapsed',
      },
      {
        key: 'storm-eye-strike-loop',
        trigger: 'time',
        repeatInterval: 12,
        action: 'trigger-hazard',
        hazardType: 'lightning',
        duration: 1.6,
        message: 'Storm strike',
      },
    ],
    shortcuts: [
      {
        key: 'storm-eye',
        name: 'Storm Eye',
        condition: 'perfectTimingOrProtection',
        width: 42,
        accent: '#a78bfa',
        points: [
          { x: 440, y: 386 },
          { x: 512, y: 324 },
          { x: 590, y: 386 },
          { x: 512, y: 460 },
        ],
      },
    ],
    hazards: [
      { key: 'lightning-beat-a', type: 'lightning', progress: 0.22, layer: 'air', side: 8, radius: 13, cycle: 4, openStart: 0.1, openEnd: 0.22, effect: 'spin', severity: 1.05 },
      { key: 'lightning-beat-b', type: 'lightning', progress: 0.5, layer: 'hybrid', side: -2, radius: 16, cycle: 4, phase: 0.5, openStart: 0.1, openEnd: 0.22, effect: 'spin', severity: 1.15 },
      { key: 'lightning-beat-c', type: 'lightning', progress: 0.78, layer: 'air', side: 10, radius: 13, cycle: 3.2, phase: 0.25, openStart: 0.1, openEnd: 0.25, effect: 'spin', severity: 1.05 },
      { key: 'tornado-skim-a', type: 'tornado', progress: 0.42, layer: 'hybrid', side: -8, radius: 17, effect: 'pull', force: 26 },
      { key: 'tornado-skim-b', type: 'tornado', progress: 0.64, layer: 'hybrid', side: -10, radius: 17, effect: 'pull', force: 24 },
      { key: 'bridge-cracks-a', type: 'bridgeCollapse', progress: 0.25, layer: 'ground', side: 0, radius: 14, active: false, targetVehicle: 'plane', effect: 'force-switch' },
      { key: 'static-charge-a', type: 'staticCharge', progress: 0.58, layer: 'ground', side: 0, radius: 15, effect: 'switch-lock', duration: 5 },
      { key: 'wind-gust-a', type: 'windGust', progress: 0.72, layer: 'air', side: 8, radius: 18, cycle: 5.6, openStart: 0.3, openEnd: 0.56, effect: 'knock-back', force: 30 },
    ],
    scenery: [
      { kind: 'spire', x: 512, y: 384, w: 102, h: 240, color: '#a78bfa' },
      { kind: 'mesa', x: 226, y: 216, w: 190, h: 110, color: '#4f46e5' },
      { kind: 'mesa', x: 820, y: 258, w: 204, h: 120, color: '#5b4bd8' },
      { kind: 'storm', x: 520, y: 650, w: 500, h: 160, color: '#6d36d8' },
    ],
    points: [
      { x: 132, y: 524 },
      { x: 188, y: 286 },
      { x: 344, y: 142 },
      { x: 526, y: 186 },
      { x: 684, y: 112 },
      { x: 884, y: 248 },
      { x: 782, y: 420 },
      { x: 914, y: 596 },
      { x: 654, y: 668 },
      { x: 512, y: 534 },
      { x: 306, y: 658 },
    ],
    aiRivals: [
      { name: 'Volt', color: '#7c3aed', accent: '#f7fbff', lane: 0.15, lineOffset: 18, aggression: 0.86, risk: 0.92, patience: 0.24, signature: 'static-bait' },
      { name: 'Surge', color: '#2cc8ff', accent: '#ffd34f', lane: 1.35, lineOffset: -16, aggression: 0.74, risk: 0.84, patience: 0.3 },
      { name: 'Nimbus', color: '#374151', accent: '#a78bfa', lane: 2.55, lineOffset: 4, aggression: 0.68, risk: 0.76, patience: 0.38 },
    ],
  },
  {
    key: 'magnet-mine-descent',
    name: 'Magnet Mine Descent',
    shortName: 'Mine Descent',
    discipline: 'Polarity',
    difficulty: 'Intermediate',
    difficultyWhy: 'The fastest route comes from reading polarity strips, gate timing, and downhill shortcut openings rather than pure reflexes.',
    laps: 3,
    width: 88,
    bananaCount: 10,
    bananaPlacements: [
      { progress: 0.04, side: -0.14 },
      { progress: 0.13, side: 0.16 },
      { progress: 0.22, side: -0.18 },
      { progress: 0.33, side: 0.18 },
      { progress: 0.44, side: -0.12 },
      { progress: 0.55, side: 0.16 },
      { progress: 0.66, side: -0.16 },
      { progress: 0.76, side: 0.18 },
      { progress: 0.86, side: -0.14 },
      { progress: 0.95, side: 0.16 },
    ],
    startProgress: 0.76,
    raceStyle: 'technical',
    accent: '#ff5fd2',
    asphalt: '#394148',
    curbA: '#f4e5c8',
    curbB: '#ff5fd2',
    grass: '#20262b',
    hazard: '#8e315f',
    sky: '#14151b',
    theme: {
      atmosphere: 'Abandoned magnetic ore mine descending around a central shaft and opening into glowing caverns.',
      time: 'Underground dusk',
      weather: 'Dust, dripping water, metallic echoes, and magnetic pulses',
      music: 'Heavy mechanical rhythm with metal clangs and low drill hits',
    },
    layout: {
      philosophy: 'Reward observation, polarity timing, and downhill line planning.',
      shape: 'A descending spiral inside a massive mine shaft with wall-drive strips, rail crossings, and a bottom drill chamber.',
      keyTurns: ['Ore-vein wall ride', 'Mine-cart crossing', 'Drill chamber drop'],
      elevation: ['Ground route clings to magnetized walls and ceiling strips', 'Air route is risky because pulses yank planes toward walls', 'Hybrid route flips gravity and demands plane control through inverted sections'],
      branches: [
        'Ground layer is safest and uses polarity strips for wall/ceiling lines.',
        'Air layer is shorter but exposed to magnetic pulses.',
        'Hybrid layer dives through the drill shortcut once opened.',
      ],
    },
    landmarks: [
      'Massive central drill at the mine bottom',
      'Glowing ore veins in the walls',
      'Abandoned mine carts crossing on rails',
    ],
    signatureObstacles: [
      'Mine carts cross on rails and knock racers sideways.',
      'Magnetic spikes snap onto karts and slow them until shaken off.',
      'Pulse zones briefly invert left/right controls.',
      'Falling stalactites are telegraphed by shadows before impact.',
      'Polarity gates only pass racers with matching polarity.',
    ],
    dynamicElements: [
      'The central drill activates on lap two and opens the bottom shortcut.',
      'Polarity strips rotate alignment every 20 seconds.',
      'Drill can trigger early when the Drill rival falls to fourth or fifth place.',
    ],
    riskRewardShortcut: {
      name: 'Shaft Drop',
      summary: 'A vertical drop straight down the mine shaft saves eight seconds if the lower platform landing is clean; miss and the checkpoint reset costs six seconds.',
    },
    powerUpIntel: {
      placement: 'Five ground boxes include wall and ceiling polarity strip placements, three air boxes sit inside magnetic pulse gaps, and two rare boxes sit in the drill shortcut.',
      signatureUse: 'Polarity Swap reverses every opponent alignment for three seconds and can drop rivals off walls or ceilings.',
      defensive: 'Before polarity gates and magnetic spike clusters.',
      aggressive: 'At the drill shortcut and ceiling-drive sections.',
    },
    aiIntel: {
      line: 'Methodical AI prefers the ground route and uses magnetic surfaces aggressively.',
      shortcuts: 'Rivals avoid air except for the shaft drop and drill shortcut.',
      items: 'Polarity Swap is saved for wall/ceiling sections.',
      signatureMove: 'Drill triggers the central drill early on lap one when in fourth or fifth place.',
    },
    signatureItem: {
      key: 'polaritySwap',
      name: 'Polarity Swap',
      summary: 'All-opponents area effect that reverses magnetic alignment for three seconds.',
      color: '#ff5fd2',
    },
    boostPads: [0.1, 0.38, 0.64, 0.88],
    itemBoxes: [0.12, 0.26, 0.44, 0.62, 0.82],
    layers: {
      ground: {
        name: 'Polarity wall line',
        vehiclePreference: 'kart',
        aiWeight: 1.12,
        lineOffset: -0.14,
        itemBoxes: [
          { progress: 0.12, side: -0.24 },
          { progress: 0.26, side: 0.24 },
          { progress: 0.44, side: -0.28 },
          { progress: 0.62, side: 0.26 },
          { progress: 0.82, side: -0.24 },
        ],
      },
      air: {
        name: 'Pulse shaft air line',
        vehiclePreference: 'plane',
        aiWeight: 0.78,
        lineOffset: 0.42,
        itemBoxes: [
          { progress: 0.2, side: 0.32 },
          { progress: 0.52, side: 0.34 },
          { progress: 0.74, side: 0.3 },
        ],
      },
      hybrid: {
        name: 'Drill shortcut',
        vehiclePreference: 'hover',
        aiWeight: 1.02,
        lineOffset: -0.4,
        itemBoxes: [
          { progress: 0.68, side: -0.36, rare: true, pool: ['polaritySwap', 'invincibility', 'boost'] },
          { progress: 0.72, side: -0.34, rare: true, pool: ['polaritySwap', 'ghostReplay', 'bananaMagnet'] },
        ],
      },
    },
    switchPads: [
      { key: 'wall-kart-pad', progress: 0.18, targetVehicle: 'kart', layer: 'ground', radius: 8 },
      { key: 'inversion-plane-pad', progress: 0.52, targetVehicle: 'plane', layer: 'hybrid', radius: 8 },
      { key: 'drill-hover-pad', progress: 0.66, targetVehicle: 'hover', layer: 'hybrid', radius: 8 },
      { key: 'bottom-kart-pad', progress: 0.78, targetVehicle: 'kart', layer: 'ground', radius: 8 },
    ],
    vehicleZones: [
      { key: 'wall-drive-kart-only', progress: 0.26, vehicle: 'kart', action: 'auto-switch', radius: 16 },
      { key: 'inverted-plane-section', progress: 0.54, vehicle: 'plane', action: 'auto-switch', radius: 18 },
      { key: 'drill-shortcut-open', progress: 0.68, vehicle: 'hover', action: 'auto-switch', radius: 18, active: false },
    ],
    vehicleLocks: [
      { key: 'inverted-plane-lock', start: 0.5, end: 0.6, vehicle: 'plane' },
      { key: 'drill-shortcut-lock', start: 0.66, end: 0.74, vehicle: 'hover' },
    ],
    events: [
      {
        key: 'lap-two-drill-activation',
        trigger: 'lap',
        lap: 2,
        action: 'activate-zone',
        zoneKey: 'drill-shortcut-open',
        active: true,
        message: 'Drill shortcut open',
      },
      {
        key: 'polarity-rotation-loop',
        trigger: 'time',
        repeatInterval: 20,
        action: 'rotate-polarity',
        message: 'Polarity rotated',
      },
      {
        key: 'stalactite-loop',
        trigger: 'time',
        repeatInterval: 16,
        action: 'trigger-hazard',
        hazardType: 'stalactite',
        duration: 2.4,
        message: 'Ceiling drop',
      },
    ],
    shortcuts: [
      {
        key: 'shaft-drop',
        name: 'Shaft Drop',
        condition: 'cleanLanding',
        width: 40,
        accent: '#ff5fd2',
        points: [
          { x: 520, y: 260 },
          { x: 548, y: 386 },
          { x: 516, y: 526 },
          { x: 458, y: 620 },
        ],
      },
    ],
    hazards: [
      { key: 'mine-cart-a', type: 'mineCart', progress: 0.18, side: 0, radius: 13, cycle: 5.2, openStart: 0.2, openEnd: 0.36, effect: 'knock-back', force: 30 },
      { key: 'magnetic-spikes-a', type: 'magneticSpike', progress: 0.34, side: -7, radius: 12, effect: 'slow' },
      { key: 'pulse-zone-a', type: 'pulseZone', progress: 0.48, side: 0, radius: 15, cycle: 7, openStart: 0.38, openEnd: 0.56, effect: 'control-flip', duration: 2.4 },
      { key: 'stalactite-a', type: 'stalactite', progress: 0.58, side: 4, radius: 14, cycle: 8.5, openStart: 0.5, openEnd: 0.62, effect: 'spin' },
      { key: 'polarity-strip-positive', type: 'polarityStrip', progress: 0.22, side: -4, radius: 12, polarity: 1, effect: 'set-polarity', duration: 5 },
      { key: 'polarity-strip-negative', type: 'polarityStrip', progress: 0.5, side: 4, radius: 12, polarity: -1, effect: 'set-polarity', duration: 5 },
      { key: 'polarity-gate-a', type: 'polarityGate', progress: 0.7, side: 0, radius: 15, polarity: 1, effect: 'polarity-check' },
      { key: 'polarity-gate-b', type: 'polarityGate', progress: 0.86, side: 0, radius: 15, polarity: -1, effect: 'polarity-check' },
    ],
    scenery: [
      { kind: 'drill', x: 512, y: 612, w: 150, h: 190, color: '#ff5fd2' },
      { kind: 'ore', x: 238, y: 238, w: 120, h: 80, color: '#4ade80' },
      { kind: 'ore', x: 820, y: 318, w: 140, h: 92, color: '#2cc8ff' },
      { kind: 'rails', x: 512, y: 416, w: 500, h: 60, color: '#6b7280' },
    ],
    points: [
      { x: 146, y: 292 },
      { x: 298, y: 156 },
      { x: 536, y: 124 },
      { x: 764, y: 210 },
      { x: 860, y: 388 },
      { x: 742, y: 552 },
      { x: 548, y: 638 },
      { x: 334, y: 604 },
      { x: 214, y: 462 },
      { x: 354, y: 336 },
      { x: 548, y: 286 },
      { x: 664, y: 394 },
      { x: 560, y: 508 },
      { x: 410, y: 468 },
    ],
    aiRivals: [
      { name: 'Drill', color: '#a16207', accent: '#ff5fd2', lane: 0.15, lineOffset: -12, aggression: 0.5, risk: 0.48, patience: 0.82, signature: 'early-drill' },
      { name: 'Quartz', color: '#64748b', accent: '#4ade80', lane: 1.35, lineOffset: 14, aggression: 0.36, risk: 0.42, patience: 0.9 },
      { name: 'Flux', color: '#7c3aed', accent: '#2cc8ff', lane: 2.55, lineOffset: -18, aggression: 0.42, risk: 0.58, patience: 0.74 },
    ],
  },

];
