import { deriveGameProfile, nextSuggestedDay } from './gameProfile.js';

export const WORLD_BOUNDS = {
  minX: -112,
  maxX: 112,
  minZ: -98,
  maxZ: 128,
};

const BASE_DESTINATIONS = [
  {
    key: 'gym',
    title: 'Gym District',
    shortTitle: 'Gym',
    icon: 'Dumbbell',
    routeFor: (state) => `day-${nextSuggestedDay(state)}`,
    position: { x: -56, z: -30 },
    entry: { x: -34, z: -22 },
    size: { w: 27, d: 21, h: 24 },
    color: '#55b957',
    accent: '#80ff62',
    districtColor: '#317842',
    banner: '#2d6f3e',
    architecture: 'gymArena',
    palette: {
      base: '#55b957',
      side: '#317842',
      trim: '#e9f7ce',
      pad: '#245d38',
      light: '#80ff62',
      roof: '#3d9349',
    },
    sign: { width: 20, height: 5.4, y: 18.2 },
    gate: { label: 'Lift', width: 24, color: '#ffd34f' },
    landmarkProps: ['barbell-towers', 'training-banners'],
    collisionPadding: 5,
    portalRadius: 13,
    autoEnterRadius: 5.8,
    metaFor: (profile) => `Day ${profile.nextDay}`,
  },
  {
    key: 'food',
    title: 'Food Court',
    shortTitle: 'Fuel',
    icon: 'Utensils',
    route: 'food',
    position: { x: 56, z: -30 },
    entry: { x: 34, z: -22 },
    size: { w: 28, d: 21, h: 18 },
    color: '#f28b2e',
    accent: '#ffbf3f',
    districtColor: '#b45f22',
    banner: '#8a3f16',
    architecture: 'foodMarket',
    palette: {
      base: '#f28b2e',
      side: '#b45f22',
      trim: '#fff0b0',
      pad: '#8a4a1f',
      light: '#ffbf3f',
      roof: '#ff9f3f',
    },
    sign: { width: 20, height: 5.1, y: 15.8 },
    gate: { label: 'Fuel', width: 24, color: '#2ec4b6' },
    landmarkProps: ['awnings', 'vendor-stalls', 'neon-sign'],
    collisionPadding: 5,
    portalRadius: 13,
    autoEnterRadius: 5.8,
    metaFor: (profile) => `${profile.foodDays} food days`,
  },
  {
    key: 'home',
    title: 'Home Base',
    shortTitle: 'Base',
    icon: 'Home',
    route: 'metrics',
    position: { x: -68, z: 34 },
    entry: { x: -42, z: 30 },
    size: { w: 26, d: 22, h: 20 },
    color: '#38a7ff',
    accent: '#dff4ff',
    districtColor: '#226aa5',
    banner: '#173c67',
    architecture: 'homeBase',
    palette: {
      base: '#38a7ff',
      side: '#226aa5',
      trim: '#f3ece0',
      pad: '#173c67',
      light: '#dff4ff',
      roof: '#1f78bd',
    },
    sign: { width: 22, height: 5.1, y: 16.4 },
    gate: { label: 'Base', width: 23, color: '#dff4ff' },
    landmarkProps: ['clubhouse-dome', 'flags', 'progress-beacon'],
    collisionPadding: 5,
    portalRadius: 13,
    autoEnterRadius: 5.8,
    metaFor: (profile) => `${profile.metricWeeks} check-ins`,
  },
  {
    key: 'lab',
    title: 'Lab',
    shortTitle: 'Lab',
    icon: 'FlaskConical',
    route: 'calibration',
    position: { x: 68, z: 34 },
    entry: { x: 42, z: 30 },
    size: { w: 23, d: 22, h: 33 },
    color: '#8a53df',
    accent: '#d45cff',
    districtColor: '#4b2a86',
    banner: '#3a246f',
    architecture: 'scienceTower',
    palette: {
      base: '#8a53df',
      side: '#4b2a86',
      trim: '#f0e2ff',
      pad: '#342061',
      light: '#d45cff',
      roof: '#6536ad',
    },
    sign: { width: 17, height: 5.1, y: 23.2 },
    gate: { label: 'Tune', width: 22, color: '#f45b69' },
    landmarkProps: ['antenna', 'dish', 'glow-tubes'],
    collisionPadding: 5,
    portalRadius: 13,
    autoEnterRadius: 5.8,
    metaFor: (profile) => `${profile.filledRMs}/${profile.totalLiftCount} lifts`,
  },
  {
    key: 'clinic',
    title: 'Clinic',
    shortTitle: 'Clinic',
    icon: 'Shield',
    route: 'joint',
    position: { x: -52, z: 92 },
    entry: { x: -30, z: 74 },
    size: { w: 26, d: 21, h: 21 },
    color: '#e64b4b',
    accent: '#ff5b68',
    districtColor: '#94313a',
    banner: '#74242f',
    architecture: 'recoveryStation',
    palette: {
      base: '#e64b4b',
      side: '#94313a',
      trim: '#f3ece0',
      pad: '#682432',
      light: '#ff9aa2',
      roof: '#b83943',
    },
    sign: { width: 19, height: 5.1, y: 16.4 },
    gate: { label: 'Recover', width: 24, color: '#d9ffe5' },
    landmarkProps: ['shield-icon', 'soft-lights'],
    collisionPadding: 5,
    portalRadius: 13,
    autoEnterRadius: 5.8,
    metaFor: (profile) => `${profile.recoveryShield} shield`,
  },
  {
    key: 'garage',
    title: 'Garage',
    shortTitle: 'Garage',
    icon: 'Wrench',
    route: 'settings',
    position: { x: 52, z: 92 },
    entry: { x: 30, z: 74 },
    size: { w: 31, d: 22, h: 19 },
    color: '#2677d8',
    accent: '#2cc8ff',
    districtColor: '#1f4f8f',
    banner: '#153765',
    architecture: 'tuningGarage',
    palette: {
      base: '#2677d8',
      side: '#1f4f8f',
      trim: '#e4f8ff',
      pad: '#153765',
      light: '#2cc8ff',
      roof: '#1d62b5',
    },
    sign: { width: 19, height: 5.1, y: 15.8 },
    gate: { label: 'Tune', width: 24, color: '#ffd34f' },
    landmarkProps: ['wide-door', 'ramps', 'tires'],
    collisionPadding: 5,
    portalRadius: 13,
    autoEnterRadius: 5.8,
    metaFor: (profile) => profile.avatar.name,
  },
  {
    key: 'raceway',
    title: 'Raceway',
    shortTitle: 'Race',
    icon: 'Trophy',
    route: 'race',
    position: { x: 0, z: 124 },
    entry: { x: 0, z: 88 },
    size: { w: 36, d: 24, h: 23 },
    color: '#2cc8ff',
    accent: '#ffd34f',
    districtColor: '#165d7a',
    banner: '#173c67',
    architecture: 'raceArena',
    palette: {
      base: '#2cc8ff',
      side: '#165d7a',
      trim: '#ffd34f',
      pad: '#153765',
      light: '#f3ece0',
      roof: '#1f78bd',
    },
    sign: { width: 20, height: 5.1, y: 17.4 },
    gate: { label: 'Race', width: 26, color: '#ffd34f' },
    landmarkProps: ['flags', 'wide-door', 'ramps'],
    collisionPadding: 5,
    portalRadius: 14,
    autoEnterRadius: 6,
    metaFor: (profile) => `${profile.race?.credits || 0} credits`,
  },
];

export const getWorldDestinations = (state, profile = deriveGameProfile(state)) =>
  BASE_DESTINATIONS.map((destination) => ({
    ...destination,
    route: destination.routeFor ? destination.routeFor(state, profile) : destination.route,
    meta: destination.metaFor ? destination.metaFor(profile, state) : '',
  }));
