export const TRACK_THEME = {
  'comeback-city': {
    fog: '#d5f9ff',
    ground: '#6fc663',
    horizon: '#bdf5ff',
    sky: '#58c8f1',
  },
  'magnet-mine-descent': {
    fog: '#1a1422',
    ground: '#211827',
    horizon: '#1f2937',
    sky: '#140f1c',
  },
  'static-storm-plateau': {
    fog: '#20284f',
    ground: '#2b315f',
    horizon: '#1f2a55',
    sky: '#18204a',
  },
  'tide-pier': {
    fog: '#bdf6ff',
    ground: '#5fa56c',
    horizon: '#6ed3ef',
    sky: '#59c6ed',
  },
};

export const createDefaultRaceCityDistricts = (palette = {}) => [
  {
    accent: palette.gym,
    base: '#3ca75b',
    dark: '#1f5f35',
    icon: 'dumbbell',
    label: 'GYM',
    progress: 0.905,
    roof: '#e9f7ce',
    side: 1,
  },
  {
    accent: palette.food,
    base: '#f28b2e',
    dark: '#9d4516',
    icon: 'utensils',
    label: 'FOOD COURT',
    progress: 0.838,
    roof: '#fff0b0',
    side: -1,
  },
  {
    accent: palette.lab,
    base: '#8a53df',
    dark: '#38206f',
    icon: 'flask',
    label: 'LAB',
    progress: 0.878,
    roof: '#f0e2ff',
    side: -1,
  },
  {
    accent: palette.clinic,
    base: '#e64b4b',
    dark: '#7c202c',
    icon: 'cross',
    label: 'CLINIC',
    progress: 0.954,
    roof: '#f3ece0',
    side: -1,
  },
  {
    accent: palette.garage,
    base: '#2677d8',
    dark: '#143d78',
    icon: 'wrench',
    label: 'GARAGE',
    progress: 0.825,
    roof: '#e4f8ff',
    side: 1,
  },
];
