// Visual portion estimates used to prefill the Manual tab with common
// restaurant and home-cooked serving assumptions.
export const PORTION_CHIPS = [
  {
    id: 'palm-lean',
    label: 'Palm — lean protein',
    category: 'protein',
    example: 'chicken breast, tilapia, tuna',
    name: 'Lean protein (palm)',
    unit: 'serving',
    servingDesc: '1 palm (≈ 4 oz / 115 g)',
    cal: 185,
    p: 35,
    c: 0,
    f: 4,
  },
  {
    id: 'palm-medium',
    label: 'Palm — medium protein',
    category: 'protein',
    example: 'sirloin, 90/10 beef, pork loin',
    name: 'Medium protein (palm)',
    unit: 'serving',
    servingDesc: '1 palm (≈ 4 oz / 115 g)',
    cal: 220,
    p: 30,
    c: 0,
    f: 10,
  },
  {
    id: 'palm-fatty',
    label: 'Palm — fatty protein',
    category: 'protein',
    example: 'salmon, ribeye, 80/20 beef',
    name: 'Fatty protein (palm)',
    unit: 'serving',
    servingDesc: '1 palm (≈ 4 oz / 115 g)',
    cal: 275,
    p: 25,
    c: 0,
    f: 18,
  },
  {
    id: 'egg',
    label: '1 egg',
    category: 'protein',
    example: 'large whole egg',
    name: 'Egg, large',
    unit: 'serving',
    servingDesc: '1 large',
    cal: 72,
    p: 6,
    c: 0,
    f: 5,
  },
  {
    id: 'fist-rice',
    label: 'Fist — rice cooked',
    category: 'starch',
    example: 'white or brown, cooked',
    name: 'Rice, cooked (fist)',
    unit: 'serving',
    servingDesc: '1 cup cooked (≈ 200 g)',
    cal: 260,
    p: 5,
    c: 56,
    f: 1,
  },
  {
    id: 'rest-fist-rice',
    label: 'Rest. fist — rice',
    category: 'starch',
    example: 'larger restaurant scoop / side portion',
    name: 'Rice, cooked (restaurant fist)',
    unit: 'serving',
    servingDesc: '1.5 cups cooked (≈ 300 g)',
    cal: 390,
    p: 8,
    c: 84,
    f: 2,
  },
  {
    id: 'fist-pasta',
    label: 'Fist — pasta cooked',
    category: 'starch',
    example: 'any shape, cooked',
    name: 'Pasta, cooked (fist)',
    unit: 'serving',
    servingDesc: '1 cup cooked (≈ 140 g)',
    cal: 220,
    p: 8,
    c: 43,
    f: 1,
  },
  {
    id: 'fist-potato',
    label: 'Fist — mashed potato',
    category: 'starch',
    example: 'with butter + milk, restaurant style',
    name: 'Mashed potato (fist)',
    unit: 'serving',
    servingDesc: '1 cup (≈ 210 g)',
    cal: 240,
    p: 4,
    c: 36,
    f: 9,
  },
  {
    id: 'fist-roasted-potato',
    label: 'Fist — roasted potato',
    category: 'starch',
    example: 'with a bit of oil',
    name: 'Roasted potato (fist)',
    unit: 'serving',
    servingDesc: '1 cup (≈ 150 g)',
    cal: 195,
    p: 4,
    c: 30,
    f: 7,
  },
  {
    id: 'slice-bread',
    label: '1 slice bread',
    category: 'starch',
    example: 'medium slice',
    name: 'Bread, slice',
    unit: 'serving',
    servingDesc: '1 slice',
    cal: 80,
    p: 3,
    c: 15,
    f: 1,
  },
  {
    id: 'cup-veg-nonstarch',
    label: '1 cup — cooked veg',
    category: 'veg',
    example: 'broccoli, green beans, zucchini',
    name: 'Cooked veg, non-starch (cup)',
    unit: 'serving',
    servingDesc: '1 cup cooked',
    cal: 35,
    p: 3,
    c: 7,
    f: 0,
  },
  {
    id: 'cup-leafy',
    label: '1 cup — leafy greens',
    category: 'veg',
    example: 'spinach/kale cooked, or 2 cups raw',
    name: 'Leafy greens (cup cooked)',
    unit: 'serving',
    servingDesc: '1 cup cooked',
    cal: 45,
    p: 5,
    c: 8,
    f: 1,
  },
  {
    id: 'cup-salad',
    label: '2 cups — side salad',
    category: 'veg',
    example: 'mixed greens, no dressing',
    name: 'Side salad, undressed',
    unit: 'serving',
    servingDesc: '2 cups',
    cal: 20,
    p: 2,
    c: 4,
    f: 0,
  },
  {
    id: 'thumb-oil',
    label: 'Thumb — added oil',
    category: 'fat',
    example: 'olive oil, cooking fat',
    name: 'Oil, added (thumb)',
    unit: 'serving',
    servingDesc: '1 tbsp (≈ 14 g)',
    cal: 120,
    p: 0,
    c: 0,
    f: 14,
  },
  {
    id: 'thumb-butter',
    label: 'Thumb — butter',
    category: 'fat',
    example: 'salted butter',
    name: 'Butter (thumb)',
    unit: 'serving',
    servingDesc: '1 tbsp (≈ 14 g)',
    cal: 100,
    p: 0,
    c: 0,
    f: 11,
  },
  {
    id: 'handful-nuts',
    label: 'Handful — mixed nuts',
    category: 'fat',
    example: 'almonds / cashews / peanuts',
    name: 'Mixed nuts (handful)',
    unit: 'serving',
    servingDesc: '≈ 1 oz / 28 g',
    cal: 175,
    p: 5,
    c: 6,
    f: 15,
  },
  {
    id: 'thumb-dressing',
    label: 'Thumb — salad dressing',
    category: 'fat',
    example: 'vinaigrette / ranch average',
    name: 'Salad dressing (thumb)',
    unit: 'serving',
    servingDesc: '1 tbsp',
    cal: 75,
    p: 0,
    c: 2,
    f: 7,
  },
];

export const CHIP_CATEGORIES = [
  { key: 'protein', label: 'Protein' },
  { key: 'starch', label: 'Starch' },
  { key: 'veg', label: 'Veg' },
  { key: 'fat', label: 'Fat' },
];
